---
title: "The Day the Earth Stood Still"

alternative_titles:
- "Der Tag, an dem die Erde stillstand"
- "День, когда остановилась Земля"
- "El día que paralizaron la Tierra"

imdb_id: "tt0043456"
tmdb_id: "828"
year: "1951"
