---
title: "Sex Is Zero"

original_title: "Saekjeuk shigong"

alternative_titles:
- "Horny Campus"
- "Sex Is Zero - American Pie war gestern..."
- "Saek-jeung-si-gong"
- "Секса круглый ноль"

filename: "Sex_is_Zero.srt"
language: "en"
imdb_id: "tt0341555"
tmdb_id: "16318"
year: "2002"
format: "srt"

matches:
- filename: "Sex_is_Zero.avi"
  hash: "b3c99fed087ed37f"
  filesize: "736018432"
