---
title: "Sex Is Zero"

original_title: "Saekjeuk shigong"

alternative_titles:
- "Horny Campus"
- "Sex Is Zero - American Pie war gestern..."
- "Saek-jeung-si-gong"
- "Секса круглый ноль"

imdb_id: "tt0341555"
tmdb_id: "16318"
year: "2002"
