---
title: "The Lord of the Rings: The Fellowship of the Ring"

alternative_titles:
- "Der Herr der Ringe - Die Gefährten"
- "Властелин колец: Братство кольца"
- "Il Signore degli Anelli - La compagnia dell'Anello"

imdb_id: "tt0120737"
tmdb_id: "120"
year: "2001"
