---
title: "Dragon Tiger Gate"

original_title: "Lung fu moon"

alternative_titles:
- "Врата дракона и тигра"
- "Escola do Tigre e do Dragão"
- "Long hu men"

imdb_id: "tt0482930"
tmdb_id: "15860"
year: "2006"
