---
title: "Twinkle Twinkle, Lucky Stars"

original_title: "Xia ri fu xing"

alternative_titles:
- "Powerman II"
- "My Lucky Stars 2: Twinkle Twinkle Lucky Stars"
- "Winners & Sinners 3: Twinkle, Twinkle, Lucky Stars"

imdb_id: "tt0090342"
tmdb_id: "18707"
year: "1985"
