---
title: "Once Upon a Time in China"

original_title: "Wong Fei Hung"

alternative_titles:
- "Die schwarzen Tiger von Hongkong"
- "Однажды в Китае"
- "Era Uma Vez na China"

imdb_id: "tt0103285"
tmdb_id: "10617"
year: "1991"
