---
title: "Armour of God II: Operation Condor"

original_title: "Fei ying gai wak"

alternative_titles:
- "Armour of God 2: Operation Condor"
- "Mission Adler - Der starke Arm der Götter"

imdb_id: "tt0099558"
tmdb_id: "10975"
year: "1991"
