---
title: "One Flew Over the Cuckoo's Nest"

alternative_titles:
- "Einer flog über das Kuckucksnest"
- "Gøgereden"
- "Пролетая над гнездом кукушки"

imdb_id: "tt0073486"
tmdb_id: "510"
year: "1975"
