---
title: "Out Live"

original_title: "Bichunmoo"

alternative_titles:
- "Das Geheimnis des Meisters"
- "Flying Warriors"
- "Бишунмо - летящий воин"

imdb_id: "tt0278351"
tmdb_id: "16404"
year: "2000"
