---
title: "Revenge of the Pink Panther"

alternative_titles:
- "Inspektor Clouseau - Der irre Flic mit dem heißen Blick"
- "Месть Розовой пантеры"
- "La vendetta della pantera rosa"

imdb_id: "tt0078163"
tmdb_id: "6081"
year: "1978"
