---
title: "Aachi & Ssipak"

original_title: "Huo shao hong lian si"

alternative_titles:
- "Aachi and Ssipak"
- "Ачи & Сипак: Убойный дуэт"

filename: "Aachi-and-Ssipak.srt"
language: "en"
imdb_id: "tt0972542"
tmdb_id: "22520"
year: "2006"
format: "srt"

matches:
- filename: "Aachi-and-Ssipak.avi"
  hash: "acef392bf9eb5616"
  filesize: "734035968"
