---
title: "My Left Foot"

original_title: "My Left Foot: The Story of Christy Brown"

alternative_titles:
- "Mein linker Fuß"
- "Моя левая нога"
- "Il mio piede sinistro"

imdb_id: "tt0097937"
tmdb_id: "10161"
year: "1989"
