---
title: "Once Upon a Time in the West"

original_title: "C'era una volta il West"

alternative_titles:
- "Spiel mir das Lied vom Tod"
- "Однажды на Диком Западе"
- "Uesutan"

imdb_id: "tt0064116"
tmdb_id: "335"
year: "1968"
