---
title: "The Return of the Pink Panther"

alternative_titles:
- "Der rosarote Panther kehrt zurück"
- "Возвращение Розовой пантеры"
- "Le retour de la panthère rose"

imdb_id: "tt0072081"
tmdb_id: "11843"
year: "1975"
