---
title: "Kung Fu Cult Master"

original_title: "Yi tin to lung gei: Moh gaau gaau jue"

alternative_titles:
- "Evil Cult"
- "The Evil Cult"
- "The Swordmaster"
- "Служители зла"

imdb_id: "tt0108624"
tmdb_id: "10852"
year: "1993"
