---
title: "Who Framed Roger Rabbit"

alternative_titles:
- "Falsches Spiel mit Roger Rabbit"
- "Кто подставил кролика Роджера"
- "Chi ha incastrato Roger Rabbit"

imdb_id: "tt0096438"
tmdb_id: "856"
year: "1988"
