---
title: "Dr. Wai in the Scriptures with No Words"

original_title: "Mao xian wang"

alternative_titles:
- "Jet Li: Die Schrift des Todes"
- "Dr. Wai"
- "Die Schrift des Todes"
- "Король приключений"

imdb_id: "tt0110463"
tmdb_id: "31027"
year: "1996"
