#!/usr/bin/env python

import os
import sys

from whoosh.fields import *
from whoosh import index
from whoosh.qparser import QueryParser

if not os.path.exists("index"):
    print "Please create index first"
    sys.exit()

ix = index.open_dir("index")

with ix.searcher() as searcher:
    #query = QueryParser("imdb", ix.schema).parse("tt0303678")
    query = QueryParser("movie_title", ix.schema).parse("*")
    results = searcher.search(query)
    for result in results:
        print result

