#!/usr/bin/env python

from whoosh.fields import *
from whoosh import index
from whoosh.qparser import QueryParser

ix = index.open_dir("index")

with ix.searcher() as searcher:
    #query = QueryParser("imdb", ix.schema).parse("tt0303678")
    query = QueryParser("movie_title", ix.schema).parse("Gentlemen")
    results = searcher.search(query)
    for result in results:
        print result

