---
title: "Vegas Vacation"

original_title: "National Lampoon's Vegas Vacation"

alternative_titles:
- "Die schrillen Vier in Las Vegas"
- "Viva Las Vegas - Hoppla, wir kommen!"
- "Каникулы в Yегасе"

imdb_id: "tt0120434"
tmdb_id: "11419"
year: "1997"
