---
title: "Sixty Million Dollar Man"

original_title: "Bak bin sing gwan"

alternative_titles:
- "Операция стоимостью 60 миллионов долларов"
- "Terminátor 33 1/3"

imdb_id: "tt0112446"
tmdb_id: "52324"
year: "1995"
