---
title: "The Legend of Drunken Master"

original_title: "Jui kuen II"

alternative_titles:
- "Drunken Master"
- "Drunken Master II"
- "Drunken Master 2"
- "Пьяный мастер 2"

imdb_id: "tt0111512"
tmdb_id: "12207"
year: "1994"
