---
title: "The Disappearance of Alice Creed"

alternative_titles:
- "Spurlos - Die Entführung der Alice Creed"
- "Исчезновение Элис Крид"
- "La scomparsa di Alice Creed"

imdb_id: "tt1379177"
tmdb_id: "38542"
year: "2009"
