---
title: "Saviour of the Soul"

original_title: "Gau yat: San diu hap lui"

alternative_titles:
- "Terrible Angel"
- "Sotiras ton psyhon"
- "Jiu yi: Shen diao xia lu"

imdb_id: "tt0104322"
tmdb_id: "45394"
year: "1991"
