---
title: Saviour of the Soul

original_title: Gau yat: San diu hap lui

alternative_titles:
- Terrible Angel
- Sotiras ton psyhon
- Jiu yi: Shen diao xia lu

filename: Saviour_of_the_Soul.srt
language: en
imdb_id: tt0104322
tmdb_id: 45394
year: 1991
format: srt

matches:
- filename: Saviour_of_the_Soul.avi
  hash: e543f1c1ac4903fd
  filesize: 735850496
