---
title: "Carrie"

alternative_titles:
- "De jongste dochter van satan"
- "Carrie, a Estranha"
- "Carrie: Des Satans jüngste Tochter"
- "Günah tohumu"

imdb_id: "tt0074285"
tmdb_id: "7340"
year: "1976"
