---
title: "The Lord of the Rings: The Return of the King"

alternative_titles:
- "Der Herr der Ringe - Die Rückkehr des Königs"
- "Властелин колец: Возвращение короля"
- "Il Signore degli Anelli - Il ritorno del re"

imdb_id: "tt0167260"
tmdb_id: "122"
year: "2003"
