---
title: Touch of Evil

alternative_titles:
- Im Zeichen des Bösen
- Печать зла

filename: Touch.of.Evil.1958.ReEdited.BluRay.720p.H264.srt
language: en
imdb_id: tt0052311
tmdb_id: 1480
year: 1958
format: srt

matches:
- filename: Touch.of.Evil.1958.ReEdited.BluRay.720p.H264.mp4
  hash: 6f9af839ed77adfb
  filesize: 1073725655
