---
title: "500 Days of Summer"

original_title: "(500) Days of Summer"

alternative_titles:
- "500 дней летa"
- "(500) días juntos"
- "500 jours ensemble"

imdb_id: "tt1022603"
tmdb_id: "19913"
year: "2009"
