---
title: "Once Upon a Time in China IV"

original_title: "Wong Fei Hung IV: Wong je ji fung"

alternative_titles:
- "Huang Fei Hong 4: Wang zhe zhi feng"
- "Last Hero II"
- "Geheimbund Weißer Lotus"

imdb_id: "tt0107162"
tmdb_id: "52316"
year: "1993"
