---
title: "Crocodile Dundee in Los Angeles"

alternative_titles:
- "Crocodile Dundee 3"
- "Crocodile Dundee III"
- "Крокодил Данди в Лос-Анджелесе"

imdb_id: "tt0231402"
tmdb_id: "9290"
year: "2001"
