---
title: "Operation Condor 2: The Armor of the Gods"

original_title: "Lung hing foo dai"

alternative_titles:
- "Der rechte Arm der Götter"
- "Armour of God"

imdb_id: "tt0091431"
tmdb_id: "10974"
year: "1986"
