---
title: "Vacation"

original_title: "National Lampoon's Vacation"

alternative_titles:
- "Die schrillen Vier auf Achse"
- "Каникулы"
- "Vacaciones"

imdb_id: "tt0085995"
tmdb_id: "11153"
year: "1983"
