---
title: "The Treasure of the Sierra Madre"

alternative_titles:
- "Der Schatz der Sierra Madre"
- "Сокровища Сьерра-Мадре"
- "Il tesoro della Sierra Madre"

imdb_id: "tt0040897"
tmdb_id: "3090"
year: "1948"
