---
title: Ulysses

original_title: Ulisse

alternative_titles:
- Die Fahrten des Odysseus
- The Loves and Adventures of Ulysses
- Приключения Одиссея

filename: Ulysses.pt.srt
language: pt
imdb_id: tt0047630
tmdb_id: 43194
year: 1954
format: srt

matches:
- filename: Ulysses.avi
  hash: 85ae8c918791715f
  filesize: 1468061696
