---
title: "Ulysses"

original_title: "Ulisse"

alternative_titles:
- "Die Fahrten des Odysseus"
- "The Loves and Adventures of Ulysses"
- "Приключения Одиссея"

imdb_id: "tt0047630"
tmdb_id: "43194"
year: "1954"
