---
title: "Last Life in the Universe"

original_title: "Ruang rak noi nid mahasan"

alternative_titles:
- "Leben nach dem Tod in Bangkok"
- "Последняя жизнь во Вселенной"
- "Vidas truncadas"

imdb_id: "tt0345549"
tmdb_id: "11606"
year: "2003"
