---
title: "The Cat Returns"

original_title: "Neko no ongaeshi"

alternative_titles:
- "Das Königreich der Katzen"
- "Katteprinsen"
- "Boзвращение кота"

imdb_id: "tt0347618"
tmdb_id: "15370"
year: "2002"
