---
title: "Christmas Vacation"

original_title: "National Lampoon's Christmas Vacation"

alternative_titles:
- "Hilfe, es weihnachtet sehr"
- "Рождественские каникулы"
- "Un Natale esplosivo"

imdb_id: "tt0097958"
tmdb_id: "5825"
year: "1989"
