---
title: "The Great Beauty"

original_title: "La grande bellezza"

alternative_titles:
- "La Grande Bellezza - Die große Schönheit"
- "Великая красота"
- "L'apparato umano"

imdb_id: "tt2358891"
tmdb_id: "179144"
year: "2013"
