---
title: The Great Beauty

original_title: La grande bellezza

alternative_titles:
- La Grande Bellezza - Die große Schönheit
- Великая красота
- L'apparato umano

filename: La.Grande.Bellezza.[The.Great.Beauty].2013.DVDRip.XviD.AC3.HORiZON-ArtSubs.srt
language: en
imdb_id: tt2358891
tmdb_id: 179144
year: 2013
format: srt

matches:
- filename: La.Grande.Bellezza.[The.Great.Beauty].2013.DVDRip.XviD.AC3.HORiZON-ArtSubs.avi
  hash: 5fe32beb057423b7
  filesize: 1884311552
