---
title: "Terminator 3: Rise of the Machines"

alternative_titles:
- "Terminator 3 - Rebellion der Maschinen"
- "Terminator 3 - Le macchine ribelli"
- "Терминатор 3: Восстание машин"

imdb_id: "tt0181852"
tmdb_id: "296"
year: "2003"
