{3910}{3992}Okay, ladies and gents,|Walkabout Creek Hotel.
{3995}{4061}Last chance for a coldie|before we hit the outback.
{4139}{4207}G'day, all.|I'm your hostess.
{4209}{4309}You can call me Ruby or love or|anything, but never late for breakfast.
{4311}{4370}[ Laughing ]
{4371}{4449}And what's your pleasure, folks?
{4451}{4522}Gin and tonic, please,|and a Pims for the lady.
{4523}{4547}Gin and tonic, please,|and a Pims for the lady.
{4550}{4593}"G" and "T" and a Pims.
{4670}{4726}No, I asked for|a gin and tonic and a Pims.
{4728}{4800}Yeah, well,|there's no harm in asking.
{4855}{4902}Couple of beers|will be just fine.
{4904}{4944}That's the ticket, old mate.
{5019}{5069}- Hey, Nugget.|- G'day, Sue.
{5070}{5181}- Where's Mick?|- We got a panic call from the Rangers.
{5183}{5281}They spotted a huge croc|in the Tarrabool swimming hole.
{5283}{5402}Actually, we tossed a coin to see|who'd catch it, and Mick won.
{5404}{5462}- He went after it alone, did he?|- No.
{5464}{5527}Jacko Jackson's gonna|meet him out there.
{5529}{5596}And Jacko, as you know, is the second|best crocodile man in the territory.
{5598}{5635}So you got no worries, love.
{5637}{5711}My only worry is I need Mick|to pick Mikey up after school.
{5713}{5783}I'll tell Mick for you.|If he gets tied up with that croc,
{5785}{5852}- I'll pick up the young fella myself.|- Thanks.
{5854}{5909}I thought you were|the second best crocodile hunter.
{5911}{5989}- Oh, well.|- Oh, he's just modest.
{5990}{6048}He's one of the best,|you know?
{6119}{6226}Hey, Sue. If anything ever happens|to Mick, I'm gonna come courtin'.
{6270}{6353}Well, let's just hope|nothing happens to Mick.
{6820}{6908}Now, where are you,|you big ugly bugger?
{7373}{7445}This is as good as it gets.
{7923}{7997}Come on.|Come to Uncle Mick.
{8093}{8170}Big...
{8172}{8218}big...
{8252}{8300}big mistake.
{8535}{8585}Oh, shit.
{8835}{8882}[ Sighs ]
{9350}{9453}- G'day, Mick.|- G'day, Jacko.
{9455}{9502}What are you doing up there?
{9504}{9621}Just sittin' up here, thinking|about a new career, mate.
{9666}{9726}Where's your boat?
{9771}{9822}On the bottom.
{9824}{9945}- How'd that happen?|- Croc pulled it under.
{9946}{9993}Pulled it under?
{10037}{10083}How big was it?
{10266}{10313}That big.
{10395}{10445}Now what?
{10447}{10549}Well, now we scramble ashore|and go to plan "B. "
{10655}{10702}Don't move.
{10791}{10841}Well, could be worse, mate.
{10843}{10902}Oh, yeah?|How's that, Mick?
{10904}{10977}Well, someone could|see us up here,
{10979}{11051}up the tree, outsmarted|by a bloody crocodile.
{11054}{11149}- [ Chattering]|- [ Groans ]
{11151}{11198}[ Chattering Continues ]
{11276}{11372}[Woman ] So help me God, if I see|a snake, I'm gonna drop dead.
{11430}{11540}How are they gonna catch a crocodile|up there in the tree?
{11542}{11680}So, which one is the second best|crocodile hunter in the land?
{11682}{11704}[ All Laughing ]
{11706}{11772}Okay, everyone, we're on|a tight schedule here.
{11774}{11841}We better keep moving.|Don't want to disturb the hunters.
{11843}{11905}Back on the bus,|please, folks.
{11960}{12006}That's the way.
{12164}{12248}Bloody Nugget.|Great, eh, mate?
{12250}{12316}Two best crocodile hunters|in the entire Northern Territory, eh?
{12318}{12364}Yeah.
{12402}{12449}We look like a couple|of real pelicans, don't we, eh?
{12450}{12527}[ Both Laughing ]
{13022}{13097}You know what I hate about crocs?|They got legs. Come on.
{13196}{13278}Oh, remember the good old days|when we just used to shoot 'em?
{13279}{13413}Yeah, mate, but if there were no more|crocs, they wouldn't need hunters.
{13416}{13537}Oh, they'd need hunters...|to keep the wild pigs in control.
{13538}{13607}Pigs?|Oh, not the same.
{13609}{13729}I don't want my kid saying,|"There goes my dad, Pig Dundee. "
{13731}{13778}Do you want to be known|as Porker Jackson?
{13780}{13821}Well, no.
{13823}{13924}Nah, we need the crocs, mate.|They make us somebodies.
{13926}{13989}Without 'em, we're|just a couple of old bushwhackers...
{13990}{14052}with bite marks on our legs.
{14054}{14109}We'll get him tomorrow.|Same time.
{14111}{14209}Hey, I knew a pig farmer called|Porker O'Brien once. Hah!
{14211}{14289}You know why|they called him Porker?
{14392}{14458}I hate it when he does that.
{14460}{14506}Gives me the creeps.
{14931}{14978}- Thanks, mate.|- No worries.
{15181}{15288}So, you got out of that tree|all right, eh?
{15290}{15374}Now, how could you possibly|know about that already?
{15376}{15505}My people have ways of talking|that no white man can understand.
{15506}{15613}Arthur, you're so full of bullshit.
{15615}{15667}No, it's a kind|of mental telepathy, eh?
{15669}{15779}- Yeah, mental, all right.|- [ Cell Phone Ringing]
{15782}{15853}Ah, I think we just found out|which one of us is the white man.
{15854}{15901}Yeah?
{15934}{15984}Yeah, I heard about that.
{16034}{16089}[ Laughing ] Yeah, well,|he's standin' right next to me now.
{16090}{16184}- Oh, great.|- Yeah, okay. Yeah, later.
{16255}{16314}- So, are you doin' a show tonight?|- Yeah.
{16316}{16408}Already did the matinee.|Gotta keep the tourists happy, eh?
{16410}{16505}Oh, well, mate, these days|they're our bread and butter.
{16508}{16641}That's sort of what we are now in|the 20th century-- tourist attractions.
{16643}{16694}As they say,|that's show business, mate.
{16696}{16749}By the way, Mick,
{16751}{16794}it's the 21 st century, mate.
{16795}{16796}it's the 21 st century, mate.
{16798}{16865}Oh, yeah, I-I knew that.
{16946}{16996}- See you, Art.|- See you later.
{16998}{17044}- See ya, Troy.|- See ya, Mikey.
{17046}{17096}- Wanna go fishing?|- Yeah.
{17192}{17281}- So, what did you learn today?|- Oh, just school stuff.
{17282}{17318}But we had an earthquake video,
{17321}{17383}and we learned how they happen|in California, America.
{17386}{17457}- Did you see one when you were there?|- No, I was in New York.
{17459}{17506}They don't have|earthquakes there.
{17507}{17611}People there wouldn't stand for it.|They'd be like,
{17613}{17706}[ Imitating New York Accent ]|"Earthquake? Hey, this is Brooklyn.
{17708}{17795}Get outta here.|Forget about it. "
{17797}{17843}They're tough.
{17868}{17973}Whoa, homework time.|What's that?
{18010}{18124}- It's goanna turd.|- That means he's close by. Find him.
{18408}{18454}- There he is.|- Yep.
{18690}{18781}- You hungry? Want him for dinner?|- Yuck, no way.
{18782}{18868}- Then you better miss.|- Dad, I never miss.
{18898}{18944}[ Gulping ]
{19058}{19125}Whoa.
{19126}{19186}Quick, Dad, there's a big razorback|up there. Can you do it?
{19187}{19265}- Do what?|- You know, that trick. Please.
{19267}{19327}All right, but it won't work|if you're scared. He'll smell it.
{19329}{19380}I know. I won't be scared.|I promise.
{19382}{19433}Don't look at him|till I do.
{19434}{19505}I really won't be scared|if I can carry your knife.
{20204}{20294}[ Imitates Growling ]|Cool.
{20423}{20470}[ Laughing ]
{20727}{20836}Okay, Dad, I'll talk it over|with Mick. Uh-huh.
{20866}{20961}No. No, and if we decide|we need to be married,
{20962}{21033}I promise you'll be|the first to know.
{21079}{21194}Would you like to say hello|to your grandson? Okay. Hang on.
{21195}{21278}Hey, Mikey.|Come say hi to Grandpa.
{21343}{21390}Hi, Grandpa.
{21421}{21477}Pretty good, yeah.
{21479}{21549}- [ Sighs ]|- So, what's new?
{21550}{21640}Oh, Tom Zetland-- he ran|the L. A. bureau of Dad's paper--
{21642}{21688}was just killed|in a car accident.
{21690}{21779}- What, was he a mate of yours?|- Actually, no.
{21781}{21893}But the thing is, Mick, Dad is now|pleading with me to take his place...
{21894}{21966}while he looks|for a permanent replacement.
{21967}{22067}What you're sayin' is your dad wants|you to go work for him in Los Angeles.
{22069}{22107}Mm.
{22109}{22173}For how long?
{22176}{22294}Well, I told him I might|fill in for a few weeks.
{22421}{22500}Well, tell me this, if we lived|over there in the city,
{22502}{22548}- would you take the job then?|- Oh, sure.
{22550}{22617}I mean, I was raised|by a newspaperman,
{22618}{22741}and, well, I don't know, I guess|it just gets in your blood.
{22742}{22829}That settles it then.|Take the job.
{22830}{22932}At least for the rest of the year.|Me and Mikey'll go with you.
{22934}{23028}- You're kidding?|- No. Good for him. Help him decide.
{23030}{23087}Decide?
{23089}{23138}- Your dad owns a newspaper, right?|- Mm-hmm.
{23141}{23222}You're his only child. Someday|Mikey's gonna have to decide.
{23224}{23270}Does he want to be an assistant|crocodile wrangler...
{23272}{23336}or the owner|of a big-city newspaper?
{23338}{23436}That's a tough one.|And the travel will be good for him.
{23438}{23507}Remember how my trip|to New York...
{23509}{23592}sort of opened my eyes|to the ways of the world?
{23593}{23667}Made me a lot more--|What's the word?
{23669}{23757}- Sophisticated?|- Yeah.
{23812}{23861}By the way, Mick, what are|you doing with that awful trap?
{23864}{23912}You're not going to use that|on some poor animal?
{23914}{23943}No, I'm lending it to Donk.
{23945}{24000}Some mongrel's been sneaking|into the pub at night...
{24002}{24038}and knocking off his grog.
{24040}{24096}[ Chuckles ]|Stealing Donk's beer, well,
{24098}{24165}- I guess they deserve to be mangled.|- Yeah.
{24166}{24242}Well, what about you, Mikey?|What do you think?
{24334}{24413}How would you like to live|in California for a while?
{24414}{24496}- They have earthquakes there, right?|- Well, yeah, they have had.
{24498}{24541}Cool.
{24543}{24645}I thought you might say that.|You're gonna have lots of fun.
{24647}{24725}Actually, you're the one|I'm worried about.
{24799}{24852}No, I'm fine.
{24931}{25026}Um, Mick, I seem to remember|after a few weeks in New York...
{25028}{25067}you did get pretty antsy.
{25069}{25125}Yeah, a bit antsy.
{25127}{25241}Mm, that's what I love about you, Mick.|You're always so unselfish.
{25286}{25332}No worries.
{25728}{25789}# Yeah #
{25831}{25925}# Yeah|Dance, dance, dance, dance#
{25926}{26024}## [ Woman Vocalizing,|Indistinct ]
{26442}{26512}[Mick ] Beverly Hills, eh?|Home to the movie stars.
{26514}{26537}A lot of 'em, yep.
{26538}{26593}You're not in show business,|are ya?
{26594}{26666}- No, I'm in the tourism game myself.|- Hey, so am I.
{26668}{26757}When I'm out driving this.|Actually, though, I'm a writer-actor.
{26759}{26835}Just, you know, drive the limo|between gigs. Make a lot of connections.
{26837}{26889}Had Tom Arnold in the car|this morning.
{26891}{26964}Tom Arnold?
{26966}{27041}Oh, wife probably knows who he is.|She's- She's in the newspaper business.
{27043}{27090}- A reporter.|- Yeah.
{27091}{27157}Here, take one of these.|You never know.
{27256}{27309}Thanks.
{27392}{27449}There you go.
{27524}{27552}That- That's nice.
{27554}{27621}No, you can keep that.|I got plenty of copies.
{28658}{28705}Crocodile!
{28926}{28992}[Sue ] Okay, tax relief plan.|State tax only.
{28994}{29060}No interest there.|Traffic accidents.
{29062}{29180}Okay, these figures comparing L. A.|to New York drivers, that's good.
{29182}{29210}Follow through on that.
{29212}{29261}Great. So our policy|hasn't changed then?
{29262}{29320}- How so?|- It's like Mr. Zetland used to say,
{29322}{29373}[Imitating Mr. Zetland]|"We're a New York paper.
{29375}{29446}If the news ain't about New York,|then who gives a rat's ass? "
{29448}{29495}Or words to that effect.
{29497}{29566}So he wasn't too happy|about working in L. A., huh?
{29567}{29656}Oh, no, no. Tom loved it here.|No, he loved doing expose features...
{29658}{29725}and investigating|scams and phonies.
{29727}{29815}- What was he working on?|- He was doing this feature...
{29818}{29906}on this new mini studio.
{29909}{29978}He started to get|really excited about it.
{29979}{30050}I think he smelled a rat.
{30053}{30097}But what it was about,|only Tom knew.
{30167}{30249}Maybe you can find out what sparked|his interest in there. Good luck.
{30363}{30436}Oh, hey, how are your boys doing?|Are they out exploring?
{30438}{30537}Oh, yeah. Should be fun too.|For both of them.
{30539}{30610}- [ Chattering]|- [Man ] Come on, people!
{30654}{30758}Thank you. Oh, spontaneous|applause, thank you.
{30970}{31024}Thank you.
{31026}{31093}All right, a couple of tricks.|Behind the back.
{31245}{31321}All right, all right,|all right, under the leg.
{31323}{31391}[Juggler Chattering ]
{31393}{31440}- [ Bones Cracking ]|- [ Man Groaning ]
{31540}{31617}[Juggler Continues|Chattering ]
{31619}{31666}[ Groaning Continues ]
{31986}{32051}Hey, Dad, look.|There's those girls from Baywatch.
{32053}{32093}- What?|- Baywatch.
{32095}{32198}On TV, you know?|The girls that run funny, like this.
{32201}{32286}And Donk and all the men|in the pub go, "Whoa! "
{32289}{32370}- What've you been doin' in the pub?|- Whoa! Hey!
{32372}{32449}- I am so sorry. Whew, muscle fatigue.|- It's okay.
{32450}{32518}- You all right?|- Hey, do you know what time it is?
{32520}{32594}Oh, it's about 12:30,|maybe 12:35.
{32596}{32666}[ Chuckles ] Oh, that's cute,|but you're wearing a watch.
{32667}{32737}- That's not a watch, it's a compass.|- Oh!
{32738}{32808}Yeah, I'm new in town.|I couldn't find my house without this.
{32810}{32869}Really? So where's|your house from here?
{32870}{32960}Eleven point five miles,|two degrees north northeast.
{32962}{33005}Called, uh, Beverly Hills.
{33007}{33079}Bev Hills?|So, you have a nice home?
{33082}{33181}- Yeah, we got eight dunneys.|- Yeah, that's eight bathrooms.
{33182}{33245}- Oh, nice. This-This your boy?|- Yeah, that's Mikey.
{33274}{33349}- So, you married?|- No, he's not married.
{33350}{33433}- So you got custody?|- Yeah. Well, Mikey's my son.
{33434}{33519}- Right. So you're a good parent?|- Well, I'd say.
{33521}{33628}Right. Oh, this is too good.|I finally bump into a cute cowboy.
{33630}{33698}He's more Robert Redford's vintage|than Brad Pitt's, but that's okay...
{33700}{33780}'cause he's got a mansion in Beverly|Hills, plus he's got custody of his kid.
{33782}{33839}That means he'd be a good dad|to my Cindy and this is--
{33842}{33869}Oh, there's a catch, right?
{33872}{33928}Nothing this good|ever happens to me.
{33930}{34024}Are you-- You're not available?|You're- You're gay, right?
{34027}{34098}Um, most of the time,|pretty happy, yeah.
{34099}{34161}[ Chuckles ]|Of course.
{34162}{34225}Cute cowboy, Venice Beach,|had to be gay.
{34226}{34273}What was I thinking?
{34310}{34424}- Boy, she was a chatterbox.|- Yeah, mate. American woman.
{34469}{34567}- She's got a nice ass.|- Yeah. Hey,
{34569}{34619}you gotta stop hangin'|around that pub.
{34670}{34738}[ Sighs ]|Who taught you that? Nugget?
{34791}{34905}- Find anything fishy?|- Yeah. Listen to this.
{34907}{34993}Silvergate Pictures make their|first movie, right? Lethal Agent.
{34994}{35041}It's a total bomb.
{35042}{35114}So the very next picture|they make is Lethal Agent II...
{35115}{35203}which, of course, goes straight|to video where no one rents it.
{35205}{35285}And guess what they're doing now|to save their reputation?
{35286}{35333}- Uh--|- Yeah.
{35377}{35424}I don't know.|Did Tom talk to these guys?
{35426}{35530}Yeah. I think he spoke to everybody|from the president of the studio down.
{35532}{35589}That's when he seemed to get|really excited about the story.
{35591}{35717}All I can see here is a bunch of|really dumb business decisions.
{35718}{35765}But, of course,|that's not illegal.
{35766}{35825}Well, you know, that's|the research I did for him.
{35826}{35896}Whatever Tom was working on|is probably in his P. C.
{35898}{35957}I can get the disk from his house,|if you're interested.
{35959}{35977}That'd be great.
{36019}{36145}And I notice they're having a "meet and|greet" for press and industry people.
{36147}{36194}Do you know who would|normally cover that?
{36197}{36229}Fay Olson does entertainment.
{36231}{36326}Okay. Tell her she can have|the night off, and I'll fill in.
{36446}{36547}- Hey, Dad, what sort of car is that?|- I can't look now, mate.
{36549}{36634}These California people are|nice and friendly and polite...
{36636}{36709}till they get in their cars, then|they turn into crazed wombats.
{36710}{36744}Quick, Dad, stop,|there's a dog in the road.
{36746}{36782}Where?
{37116}{37169}- So where's the dog?|- He ducked in there.
{37171}{37241}I'll get him.
{37242}{37289}Be careful.
{37373}{37471}All right, everybody, stay back.|Don't worry, we'll get him.
{37473}{37525}I'm on it.
{37526}{37567}- What's the hell's goin' on up there?|- Come on, buddy!
{37569}{37621}The guy said there's|something on the road.
{37623}{37656}He looks like a nut to me.
{37658}{37717}- Probably a bomb or something.|- It's a what?
{37718}{37801}- He says it's a bomb!|- It's a bomb! It's gonna blow!
{37803}{37892}[ All Screaming ]
{37926}{38011}Come here, boy. Come on.
{38013}{38084}He won't come out.|He's scared.
{38086}{38164}That's not a dog.|That's a--
{38166}{38243}I don't know what it is.|Some kind of possum maybe.
{38245}{38293}I've never seen|a black and white possum.
{38294}{38294}I've never seen|a black and white possum.
{38297}{38365}I think it's a skunk.
{38367}{38430}How do you know what a skunk|looks like? We don't have 'em at home.
{38433}{38540}It looks like Pepe Le Pew|in the cartoons on TV. [ Chuckles ]
{38542}{38610}I thought skunks were|supposed to stink.
{38612}{38672}[ Sniffing ]|Don't stink.
{38812}{38896}Come on, boy.|Come on.
{39182}{39251}[Dispatcher Chattering]
{39253}{39311}Possible explosive device|and hostage situation.
{39313}{39359}There we go.
{39391}{39449}No wonder he's scared.
{39450}{39497}Those bloody helicopters.
{39550}{39595}Take off!
{39638}{39707}We have a very tricky situation|for the police here.
{39709}{39792}The suspect appears to be|holding a young boy hostage.
{39856}{39903}Stay where you are!
{39905}{39955}Put the bomb down!
{39957}{40007}What?
{40034}{40129}That's not a bomb.|That's a cat.
{40194}{40287}Ah, see, just like at home.|The policeman is your friend.
{40289}{40336}They're here to help us.
{40380}{40440}That's not a cat.|That's a skunk.
{40497}{40588}- You can take it from here, guys.|- Uh-uh.
{40590}{40684}Uh, Mike, I wouldn't|mention this to your mum.
{40686}{40771}She probably wouldn't understand.|It's man stuff.
{40774}{40845}Of course, at that stage,|early this afternoon,
{40846}{40950}we had no idea that the bomb|was, in fact, a skunk.
{40952}{41024}Officers reluctantly placed|the skunk in a squad car...
{41026}{41084}to await the arrival|of animal control.
{41086}{41161}In the meantime, it backed up|traffic on the 101...
{41162}{41242}[ Volume Increases ] from Calabasas|to Pasadena, the worst traffic jam--
{41244}{41336}- What are you doing, Mikey?|- Uh, it's okay, love, it's me.
{41338}{41420}Oh. Mick, are you sure|you want to come tonight?
{41422}{41492}I mean, it's a social thing,|but it'll be work for me.
{41494}{41526}I'm lookin' forward to it.
{41528}{41611}You know, to see if the local people|are as friendly as New Yorkers.
{41613}{41715}I hope your son feels the same way.|He starts school on Wednesday.
{41717}{41847}Oh, no worries.|He's, uh, he's just like me, really.
{41849}{41960}From what I hear, he has enough charm|to stop a skunk from spraying him.
{41962}{42010}Yeah, well, you know, we were|roarin' down the freeway--
{42012}{42054}It's okay.
{42056}{42179}- You looked really cute on TV.|- Bloody television.
{42182}{42227}## [Rap ]
{42761}{42806}Not this time, pal.
{42846}{42915}- [ Gasps ] Mick!|- Call the cops!
{42917}{42988}Let him go. He's the valet.|He's supposed to park the car.
{42990}{43049}Yeah, yeah,|take it easy, dude.
{43106}{43195}- Tip him.|- Sorry.
{43198}{43269}- Honest mistake.|- Sorry.
{43325}{43371}Valet?
{43373}{43432}## [Rap Continues]
{43538}{43592}- Picture, please.|- Sure.
{43660}{43700}Mind if we get a shot?
{43702}{43816}Don't worry. I'll just get|a drink, blend right in.
{43818}{43913}Okay. I'll come and get you|after I've done the formalities.
{44025}{44072}[Man ]|Big smile for the camera, please.
{44364}{44422}All right, that's your Evian,|and this here's...
{44424}{44475}your sparkling mineral water|with a twist.
{44477}{44523}Oh, and a straight club soda.
{44579}{44648}So, you havin' a drink|or doin' your laundry?
{44746}{44807}G'day. Mick Dundee.|And you're--
{44810}{44856}Tony. What can I get|for you, Mr. Dundee?
{44858}{44939}Just a cold beer'll do, mate.|Thanks.
{44941}{45018}That's typical of L. A. today.|Health nuts.
{45020}{45119}Worried about what they drink,|worried about what they eat.
{45121}{45211}I used to be like that|till I found the answer.
{45213}{45295}Oh? And, um,|what's the answer?
{45297}{45437}Coffee. Eat and drink whatever you|please, then flush it out with coffee.
{45439}{45503}So you just drink|lots of coffee.
{45505}{45640}No. You don't drink it.|I'm talking colonics.
{45642}{45733}A good coffee enema|leaves you clean as a whistle.
{45734}{45778}[ Chuckles ]|Bottoms up.
{45931}{45999}Hey, Tony.|An enema--
{46001}{46043}Isn't that where they shove|a hose up the old--
{46045}{46145}- Yep. Lots of people swear by 'em.|- With coffee?
{46224}{46303}- Cream and sugar?|- It's L. A.
{46412}{46469}Excuse me, Mr. Rothman.
{46501}{46547}I'd love to introduce you|to someone.
{46549}{46639}- Ms. Sue Charleton from Newsday.|- Hello.
{46641}{46720}Arnan Rothman. Delighted.|Didi tells me you've replaced...
{46722}{46780}- our late friend, Tom Zetland.|- [ Cell Phone Ringing]
{46782}{46854}- Excuse me.|- That's a shame. He was a good man,
{46856}{46901}and he really knew his way|around this business.
{46903}{47012}Well, I'm afraid I come up|a bit short in that department.
{47014}{47087}Actually, I was hoping|maybe you could help me out.
{47149}{47248}- Are you in the cast of this flick?|- Me? Oh, no, I'm socializing.
{47250}{47322}Networking. Me too. Have you seen|any of these masterpieces?
{47325}{47398}- No.|- Unbelievable schlock. I kid you not.
{47400}{47453}Makes you embarrassed|to be in the business.
{47455}{47528}The only thing I've seen worse than|Lethal Agent was Lethal Agent II.
{47530}{47584}I read the script on this one,|and it's even worse.
{47586}{47638}I don't know how these clowns|stay in business.
{47640}{47721}I suppose you've heard, then,|they're making Lethal Agent IV.
{47723}{47792}What?
{47794}{47856}No one told me.|Do you know if they're casting yet?
{47858}{47916}I gotta call my agent.
{47958}{48014}I'm planning on following|through on Tom's story...
{48017}{48085}more about your film company|than this particular film.
{48086}{48134}- We shot the whole thing in Greece.|- Oh!
{48135}{48209}[ Gasps ]
{48211}{48317}Allow me to introduce Milos Drubnick,|our international vice president.
{48318}{48417}- Sue Charleton.|- Delighted to meet American star.
{48418}{48466}I'm big fan, all your films.
{48468}{48541}Well, that's very kind of you,|but I'm a journalist.
{48543}{48669}- Sue's from Newsday.|- Huh.
{48671}{48730}Milos handles all our|Eastern European activity.
{48732}{48780}I could not work over there|without him.
{48782}{48828}You'll excuse me.
{48922}{48995}Well, I don't want to monopolize|all your time here.
{48997}{49068}I was hoping we could catch up|at the studio.
{49070}{49088}Absolutely.
{49132}{49199}That's just the way|they do things.
{49201}{49240}You don't want that, love.
{49242}{49318}Get some free food in you.|You'll feel a lot better.
{49320}{49366}You're welcome.
{49403}{49515}- Hey, you're from down under, right?|- Yeah.
{49517}{49569}I don't suppose you know|Mel Gibson.
{49572}{49678}Mel Gibson? Ought to.|Bailed him out of jail twice.
{49681}{49740}You're kidding.|You really do know him?
{49742}{49824}- I could tell some tales about Mad Mel.|- Please do.
{49825}{49851}- I could tell some tales about Mad Mel.|- Please do.
{49852}{49931}I thought you said we were finished|with these prying Newsday people.
{49933}{50011}She's just following up on|the original story. I'll handle it.
{50013}{50105}No. Now she want to come snooping|around studio. You should say no.
{50106}{50168}Look, we're the new boys|in town, right?
{50170}{50219}We're supposed to be begging|for publicity.
{50221}{50313}We start banning the press,|they're gonna be all over us.
{50315}{50343}Leave this to me.
{50345}{50448}- He takes his shoes off-- Thanks, Tony.|- You're welcome.
{50450}{50544}Runs outside stark naked.
{50546}{50618}Sets fire to the building|and burns it to the bloody ground.
{50620}{50685}[ All Laughing ]
{50688}{50734}He's a mad bugger.
{50772}{50818}Excuse me.
{50851}{50911}Mel Gibson's best friend.|They're practically brothers.
{50913}{50938}I've seen them together.
{50940}{50989}Just tellin' 'em a few tales|about Mel Gibson.
{50991}{51062}- You don't know Mel Gibson.|- Yeah, I do.
{51064}{51136}You know him too.|Met him at Donk's pub.
{51138}{51211}Mel Gibson. Tall redheaded fellow,|walks with a limp.
{51213}{51320}Oh, "Mal. " Malcolm Gibson.|Not Mel Gibson.
{51322}{51400}Yeah, Mal Gibson.|They know about him over here!
{51402}{51433}Small world, isn't it?
{51436}{51558}Hey, Mick. Mick,|you give me a call anytime.
{51585}{51671}Okay, dude. Hey!|Maybe we'll do lunch.
{51731}{51829}- Mick, you're starting to scare me.|- I like Hollywood.
{51900}{51965}Good afternoon.|Welcome to Beverly Hills.
{51967}{52014}Thanks.
{52086}{52166}So, your story on the film company|just got red hot.
{52168}{52238}Tom Zetland's place was robbed,|and they took everything.
{52241}{52367}Oh, my God, that's terrible.|But how does it make the story hot?
{52369}{52425}Tom is accidentally killed?
{52426}{52563}His place is cleaned out, leaving|no clues to what he's working on?
{52565}{52632}Maybe Tom was|on to something big,
{52634}{52682}and they had to shut him up.
{52684}{52765}You think the film people|had him killed?
{52766}{52815}It's possible.
{52817}{52890}I had a bad vibe about this|from the start.
{52892}{52941}I think you should be|careful going out there.
{52943}{53029}Well, I'm not exactly going|into a Mafia stronghold.
{53031}{53085}I'm interviewing|a studio head on the lot.
{53087}{53151}I'm even bringing my family along.|They're gonna do the tour.
{53378}{53472}Well, all righty, then. Welcome,|ladies and gentlemen, boy and girls,
{53474}{53537}to the Paramount Pictures tour.
{53539}{53625}This is where the magic happens,|people. But before we actually begin,
{53627}{53726}I'm gonna ask you all|to raise your right hand.
{53791}{53859}Okay, cool. Now what|you're about to witness...
{53862}{53909}are some of the biggest secrets|of movie-making.
{53912}{54032}So I must ask that all of you swear not|to reveal anything you witness here.
{54062}{54114}Do you swear?
{54149}{54205}Uh, just say, "I do. "
{54206}{54265}- [ All ] I do.|- Okay.
{54266}{54313}Righty- o, Jim.
{54534}{54615}Oh, wow, you're in for|a special treat here today, people,
{54617}{54664}'cause just up ahead|we're actually filming...
{54666}{54725}a giant crowd scene for the latest...
{54727}{54793}Silvergate Studio picture,|Lethal Agent III.
{54794}{54850}I told you we should've gone|to Universal.
{54852}{54933}Because quite simply, losses|on the first two movies...
{54934}{55018}are amortized into the cost|of the franchise.
{55020}{55085}We're making this movie|for practically nothing.
{55087}{55170}Okay, but still, wouldn't it|be cheaper to make your films...
{55171}{55262}either here or in Eastern Europe|instead of both places?
{55264}{55329}Sure, but our movies are set|in Eastern Europe.
{55331}{55392}You can't fake|the locations here?
{55394}{55459}I mean, they're shooting|an African jungle next door.
{55462}{55525}Sue, can you and I talk|off the record?
{55528}{55601}- Will you excuse us for a minute?|- Sure.
{55659}{55706}Quite frankly, the, uh,
{55707}{55818}the success or failure|of these films...
{55820}{55873}is of little importance to us.
{55910}{55975}We're after bigger fish.
{55977}{56072}There are over|300 million people...
{56074}{56145}in what was once|the Soviet bloc.
{56146}{56201}People who are starved|of entertainment.
{56202}{56327}Movies shot in their own backyard,|starring their own people.
{56330}{56412}I'm talking about building|major studios, cineplex chains,
{56414}{56452}even theme parks.
{56454}{56593}The deal I am talking about will make|Euro Disney seem penny-ante.
{56595}{56699}Well, this is a great story.|A Russian Hollywood.
{56701}{56750}And when do we go on record?
{56752}{56853}[ Sighs ]|Two weeks, tops.
{56855}{56911}But for you,
{56946}{57011}24 hours before|the rest of the world.
{57014}{57069}Exclusive to Newsday.
{57095}{57144}And in return?
{57147}{57240}Postpone the piece you've|already started. Right now, what is it?
{57242}{57315}It's a-- It's a story|about a small-time studio...
{57317}{57385}and their two|unsuccessful movies.
{57386}{57442}[ Chuckles ]|Who cares?
{57444}{57491}What do you say?
{57493}{57541}- [ Buzzing ]|- Well,
{57543}{57653}if it's a Newsday exclusive,|I guess you got a deal.
{57655}{57743}Claire, why don't you take|Ms. Charleton down to the set.
{57745}{57834}You can see the glamorous|side of the business.
{57837}{57898}I'll be in touch.
{58203}{58250}You are good.
{58251}{58332}[ Tour Guide ]... where we can transform|an ordinary man or woman...
{58334}{58383}into an ape or a clown.
{58385}{58495}All righty, then. Now, before|we enter this next portal,
{58497}{58575}it is my duty to warn you that several|dangerous jungle creatures...
{58577}{58705}have been sighted on the loose,|so keep inside the tram at all times.
{58707}{58801}I don't want to lose|anyone... again.
{58802}{58887}- Dad, do you have your big knife?|- Didn't think I'd need it here.
{58889}{58955}I might have my pocket knife.|What do you need it for?
{58957}{59043}- In case the jungle animals attack.|- I think we'll be all right.
{59079}{59157}Okay, look out, folks,|it's a giant deadly anaconda!
{59251}{59290}- [ Passengers Gasping ]|- [ Chuckling ]
{59402}{59515}- Well, that's awesome, dude.|- Sorry, reflex action.
{59518}{59561}Okay. Cool.
{59563}{59624}Let's get outta here.
{59626}{59674}[Man ]|Hey, is he part of the show, or what?
{59677}{59742}G'day.
{59744}{59829}- Was that more man stuff, Dad?|- You got that right, mate.
{59985}{60056}- Hey, you two. Did you have fun?|- Yeah, it was cool.
{60058}{60117}Yeah. So how'd your interview go?
{60192}{60247}Creepy.
{60250}{60344}Did you ever talk to someone and think|everything they're saying is a lie?
{60347}{60395}Yeah. Nugget.
{60398}{60499}Well, Nugget's harmless.|This guy--
{60501}{60600}You know what you should do? Your|paper's got police connections, right?
{60602}{60670}You get the cops to do|a background check on him.
{60672}{60740}That's the way they do it|on NYPD Blue.
{60742}{60825}Hmm. Well, I see Mikey's|not the only one glued...
{60827}{60887}to the TV all day long.
{60889}{60970}But we only watch educational|programs. Right, mate?
{60972}{61018}Yeah. Like wrestling.
{61021}{61093}"Can you smell|what the Rock is cooking? "
{61201}{61292}- Well, did he behave today?|- Yeah, he was good as gold.
{61294}{61345}I wasn't talking to you.|I was talking to Mikey.
{61347}{61384}Oh.
{61386}{61449}And no more TV.|You start school tomorrow.
{61994}{62062}G'day. Mick Dundee.
{62096}{62149}Here to pick up my ankle biter.|It's his first day.
{62150}{62213}Ah, Barry Katz.|What, uh, grade's he in?
{62215}{62280}- Uh, fourth.|- Oh, same as my boy.
{62282}{62336}My boy's in the third.|Eric Berry.
{62338}{62385}- Hi, Eric.|- Well, you look like an outdoors man.
{62386}{62453}What do you think of this|whole survival camp idea?
{62455}{62469}What is it?
{62471}{62548}The school's puttin' it on this summer.|Teach kids how to survive in the woods.
{62550}{62640}Fishing, making campfires.|Dads are welcome.
{62642}{62681}- Oh.|- [Eric ] I think it's a great idea.
{62684}{62784}Gives them a chance to get in touch|with nature. I'm gonna take Gary along.
{62786}{62838}Good for you.|Couple of weeks in the bush,
{62841}{62888}you and your boy,|you'll both love it.
{62890}{63010}You ever take your boy into the outback|where you were? Down under?
{63012}{63076}All the time.
{63078}{63129}Just last month,|I took him into the bush.
{63167}{63232}Taught him how to kill|a wild boar with a stick.
{63234}{63288}Kill a boar?|But he's, like, nine years old!
{63290}{63396}Yeah, well, you know what they say.|Better late than never, eh?
{63435}{63505}Ah.|See you later, fellas.
{63621}{63726}Hey, Dad. Ms. Mathis wants to talk|to you. I'll meet you over there.
{63728}{63786}- Dorothy Mathis, Mr. Charleton.|- Oh, how do you do?
{63788}{63861}Actually, it's Mick Dundee.|But I'm Mikey's dad.
{63863}{63897}Oh, Mr. Dundee. Right.
{63898}{64021}Well, first off, Mikey is|a lovely boy. Bright, friendly.
{64023}{64122}There's just one small problem,|one we run into all the time here.
{64124}{64170}We call it|the "Hollywood Syndrome. "
{64172}{64226}Like when a dad plays|a policeman in a movie,
{64228}{64309}the children often believe|he's actually a policeman.
{64311}{64369}Oh, right, you've got|a lot of actors' kids here.
{64371}{64476}I'm not in the movie business, I'm in|the tourism business. Not so glamorous.
{64478}{64541}Exactly. Which is why|your son tries to make it...
{64543}{64600}sound a bit more colorful|than it really is.
{64602}{64692}Now, it seems harmless,|but little fibs can grow.
{64694}{64753}What's he been sayin'?
{64755}{64829}I'm afraid he told everyone|you're a hunter,
{64831}{64909}and you hunt and kill crocodiles.|[ Chuckles Nervously ]
{64911}{64978}Oh. He knows|better than that.
{64980}{65088}Crocodiles are protected.|I don't kill 'em. I catch 'em alive.
{65120}{65192}Oh? Well, yes, of course.
{65195}{65272}I'll talk to him.|There'll be no more fibs.
{65274}{65325}Really nice to meet you, Dorothy.
{65424}{65470}Looks like a hunter.
{65584}{65662}Nice butt.
{65664}{65755}Dad, will you tell the teachers|to call me Dundee, not Charleton?
{65757}{65849}Oh, sure. We just had to enroll you|at school under your mother's name...
{65850}{65940}'cause that's your|legal name over here.
{65942}{65988}Is that 'cause|you won't marry Mum?
{65990}{66041}Oh, no, we're married...|sorta.
{66044}{66102}We just haven't done|the legal bit yet.
{66104}{66193}So what'd the kids say when you told|them your dad was a crocodile hunter?
{66194}{66290}They said, "Well, what's|he doing in Beverly Hills? "
{66292}{66338}Smart kids.
{66504}{66577}Hey, Dad,|what's that man doing?
{66579}{66686}I don't know.|Let's go and ask him.
{66790}{66864}Excuse me, mister.|What are you doing?
{66866}{66918}Well, I'm meditating,|young man.
{66920}{66966}What's meditating?
{66968}{67077}Meditating is a special place I go|in my mind where there's no distraction,
{67079}{67140}and I receive|a great source of power.
{67142}{67217}Cool. Can you|show us how, please?
{67218}{67286}Sure. Come forward|and have a seat.
{67337}{67417}- My name's Mikey. What's yours?|- Hi, Mikey. I'm Mike.
{67418}{67502}Oh, hi, Mike.|I'm Mick, Mikey's dad.
{67505}{67585}Mikey, Mick, Mike.|You gotta be kidding me, right?
{67587}{67668}- No.|- Okay, okay. Hold your legs...
{67670}{67716}like in a Buddha position,
{67718}{67774}grab your ankles to|save yourself some discomfort,
{67776}{67877}and, um, we're gonna take it easy--|close your eyes, relax.
{67878}{67941}[ Inhales Deeply ]|Inhale the positivity,
{67943}{67997}[ Exhaling ]|exhale the negativity.
{67999}{68078}Inhale the positivity,
{68080}{68126}exhale the negativity.
{68182}{68265}Open your eyes.|Wake up. Relax.
{68266}{68349}- How do you feel?|- Very powerful.
{68352}{68456}And that's the ticket, daddy-o--|power. It's all in the power.
{68458}{68553}Mikey, would you just hurry up ahead.|I need to talk to Mike for a minute.
{68555}{68609}- Okay.|- In private.
{68611}{68733}- Thanks, Mike. See ya.|- You're welcome, Mikey. Take care.
{68734}{68800}Now, Mike, I need a favor.
{68802}{68856}You know, Mick, everybody|needs a favor from me.
{68858}{68933}Well, I need you to help me up.|My knees have locked.
{68934}{69033}That's my bad right there.|You got it, buddy.
{69034}{69084}I didn't want my kid to see.|Oh! There.
{69121}{69154}Thank you.
{69204}{69292}Hey, Dad, did you see the size of|Mike's muscles? They were huge.
{69294}{69395}Yeah. You see, you should never|judge a book by its cover.
{69397}{69492}That Mike-- big man,|built like a brick dunney,
{69494}{69585}but I could tell straightaway|he was a gentle man.
{69586}{69717}He wouldn't hurt a fly.|I just know people. It's a gift.
{69758}{69820}[Man On TV] I need you guys|to tear this place apart.
{69822}{69905}Ah, it's the bowlin' ball.|Pure heroin.
{69908}{70049}- I know it's here somewhere.|- Check out the bowlin' ball.
{70050}{70137}- Hey, what about this bowling ball?|- There, I knew it.
{70138}{70185}[ Television Continues ]
{70464}{70529}- Hey, Sue!|- Hmm?
{70573}{70681}- What are you doin', love?|- Trying to think like a journalist again.
{70683}{70740}I used to be|pretty good at it.
{70742}{70775}Not that anyone was gonna put...
{70777}{70832}Sue Charleton and Pulitzer Prize|in the same sentence,
{70834}{70949}but, ah, [ Sighs ]|I'm just stumped.
{70950}{71000}Is it that, uh,|film studio thing?
{71002}{71137}I'm sure it's an elaborate front|for something. But what?
{71138}{71208}They're smugglin'.
{71210}{71284}- Drugs or guns.|- How do you arrive at that?
{71286}{71325}That's what it always is.
{71327}{71417}The big money thing they smuggle|into America are drugs.
{71418}{71481}And the big thing goin' out--|guns.
{71519}{71568}Oh.
{71571}{71685}And where did this insight into|major criminal activities come from?
{71686}{71741}Oh, from TV.|I'm a quick learner.
{71743}{71830}I look like I just fell off the turnip|truck, but I didn't land on my head.
{71886}{71957}You know what you need?|You need a mole.
{71958}{72070}- A mole?|- Me. I'll get a job at the studio.
{72072}{72162}Oh, Mick, I know you need|something to do, but--
{72164}{72225}I made a lot of contacts|at that movie party.
{72227}{72284}I bet one of them|could get me a job there.
{72286}{72349}Well, what about Mikey? Who's gonna|take him to school in the morning?
{72352}{72408}I'll get him one of those nannies.|I'll get a good one.
{72410}{72501}No worry. Leave it to me.|This is important.
{72502}{72611}See, sometimes I think young Mikey|thinks I'm a bit of a hillbilly.
{72613}{72677}Well, I am, actually.
{72679}{72782}I wanna show him that being a hillbilly|doesn't necessarily mean you're dumb.
{72783}{72784}I wanna show him that being a hillbilly|doesn't necessarily mean you're dumb.
{72786}{72858}[ Man ] So our first group,|stroll up the street,
{72860}{72949}followed by our three businessmen|at a more brisk pace...
{72950}{73009}and then our two|construction workers!
{73044}{73121}- Diego Rosales.|- Yeah, Mick. Mick Smith.
{73122}{73168}Nice to meet you, Mick.
{73170}{73261}Now, we're in Berlin,|so please walk like Germans!
{73287}{73347}How do Germans walk?
{73350}{73424}- One foot after the other?|- Okay.
{73426}{73528}So, this is a rehearsal!|Background only!
{73530}{73587}And... action!
{73733}{73772}What the hell are you doing?
{73774}{73837}I just wanted my kid|to see me in the picture.
{73838}{73928}Yeah, well, if you start looking|at the camera during the take,
{73930}{73981}- they'll take you out of the picture.|- Oh.
{73984}{74080}- You're new, aren't you?|- Yeah, first role. Bit nervous.
{74082}{74165}Cut!|Back to one, please!
{74167}{74249}- Just relax. Watch me, okay?|- Yeah.
{74250}{74287}Forget about the camera.
{74289}{74357}We're two working stiffs|on our way to a bar.
{74359}{74417}- Oh, just pretend it's real life?|- Yeah.
{74516}{74619}Okay, now, people, we will be doing it|for real this time, and remember--
{74621}{74669}attention, please!
{74671}{74774}- Quiet, everyone! Picture's up!|- Quiet!
{74777}{74843}- Roll!|- Sound speed.
{74846}{74867}Marker.
{74907}{75013}Set.|And... background action.
{75041}{75087}And action.
{75163}{75249}Stop that man!
{75291}{75377}- Cut! Cut!|- Man, are you okay?
{75379}{75480}- What the hell happened?|- It was my fault. I saw him runnin'--
{75482}{75599}Uh, what happened is that he--|he tried to catch him as he fell.
{75602}{75686}We saw him trip. He went down hard.|Are you sure you're okay?
{75730}{75831}- Thanks for trying, buddy.|- Okay, we'll go again.
{75833}{75949}Back to one! Fast as you can!|We're losing the light!
{75951}{76028}Hey, thanks|for covering up for me.
{76030}{76126}I couldn't help it, you know? Reflex.|Sort of like a football flashback.
{76128}{76211}Football, my ass.|That wasn't exactly a legal tackle.
{76213}{76349}It is at home. It's called a dowel|and coat hanger. Anyway, I owe you one.
{76350}{76421}No, no, it's okay.|I had to keep you here.
{76422}{76512}You're fun. I want to see what you're|gonna do to screw up the next take.
{76514}{76561}Okay.
{77058}{77116}Oh, uh, what's the problem,|Michael?
{77118}{77226}Miss, do people like rats|in America, or are they just pests?
{77229}{77348}- Why do you ask?|- There's a big rat in the bookshelves.
{77350}{77448}[ All Screaming ]
{77753}{77845}[ Gasping, Groaning]
{77935}{77992}- Is it dead?|- No, Miss.
{77994}{78097}I only stunned it. Dad says never kill|anything unless you're gonna eat it.
{78099}{78145}[ All ]|Eww!
{78147}{78207}I think we'll just put it|outside, please.
{78349}{78405}He's my best friend, you know?
{78407}{78528}The key to survival here is you gotta|keep your face away from the camera.
{78530}{78595}That way they can use you|again and again.
{78597}{78656}- I've been in every mob scene.|- You're a pro.
{78658}{78713}All right, everyone!|Settle down!
{78714}{78762}- Settling!|- Try again.
{78788}{78849}And background action!
{78852}{78899}Action.
{78902}{79020}Watch this! Watch this!|Kiki, get me a drink.
{79091}{79160}[ Chittering ]
{79162}{79241}Cut!|This isn't working.
{79243}{79289}What's the problem|with the monkey?
{79291}{79383}Sorry. She was fine earlier.|Come here, Kiki. Come here.
{79385}{79437}Come here.
{79439}{79512}I don't understand.|She never does this.
{79514}{79597}Come here, Kiki!
{79599}{79687}She's just a bit nervous.|What do you want her to do?
{79690}{79746}- You ever work with animals?|- Yeah.
{79748}{79823}- Kinda.|- She's supposed to go to the table...
{79825}{79872}and take a soda|to the actor.
{80013}{80093}- Diet or regular?|- Whatever. Diet.
{80186}{80253}- Want a glass?|- She hasn't learned that.
{80300}{80364}- We're running late here.|- [ Whispering ]
{80366}{80471}Can we try one more time?|If this doesn't work, we'll drop it.
{80473}{80568}Okay, back to one.|This is the real thing, everybody.
{80571}{80630}Concentrating. Roll!
{80658}{80705}- Picture's up!|- Speed. Marker.
{80776}{80851}- And background action!|- Action!
{80853}{80909}Watch this. Watch this!
{80911}{80978}Kiki, get me a drink.
{81049}{81121}Make it a diet one.
{81123}{81193}And a glass too!|Thank you, mein Liebchen.
{81195}{81265}Cut! Print!|Check the gate.
{81266}{81325}[Applause ]|Whoo!
{81374}{81439}[ Whispering ]|Book him.
{81490}{81583}Look, uh, I got a problem.|All my animals are on the jungle set,
{81585}{81642}and I can't keep coming|back and forth with the chimp.
{81644}{81710}So if you'll fill in for me,|I'll double what you're getting paid.
{81712}{81758}Will I still be on this picture?
{81760}{81833}Every day.|Kiki's an above-the-title player.
{81835}{81886}- You got a deal.|- [ Clapping]
{81917}{81973}You're looking at|the new monkey wrangler.
{81975}{82051}- Thanks for your help, Diego.|- Dude, Mick!
{82053}{82133}Hey, hey, this is|a positive career move.
{82134}{82236}- Reckon?|- I'm telling you, you're gonna go far.
{82238}{82312}Ah! Don't be a stranger now.
{82392}{82460}Hell of a nice guy.
{82461}{82536}Can't act for shit,
{82537}{82613}but he'll probably wind up|with his own TV sitcom.
{82615}{82676}- [ Kids Chattering ]|- Mikey!
{82705}{82751}Wait just a minute, dear.
{82778}{82851}- See ya, Mike.|- Bye, Mikey.
{82854}{82909}I suppose your father's|picking you up again.
{82911}{82966}Nah, he's at work this week.
{82968}{83052}Oh. Bummer. Well, how are you|getting home then?
{83054}{83101}I've got a nanny|like all the other kids.
{83102}{83173}Oh! Which one's yours?
{83174}{83225}Over there.|The big one.
{83262}{83367}- Your nanny?|- He's Uncle Jacko from back home.
{83369}{83470}- And is Uncle Jacko married?|- No, but he's looking.
{83472}{83538}Hi. Dorothy Mathis.|I'm Mikey's teacher.
{83540}{83620}G'day, Dorothy.|Call me Jacko.
{83621}{83621}G'day, Dorothy.|Call me Jacko.
{83705}{83758}Bloody marvelous.
{83790}{83869}Los Angeles, eh?
{83871}{83933}Funny name.
{83935}{83985}Los Angeles.
{83987}{84057}Yeah, it means, uh,|"lost angels. "
{84083}{84159}It's Italian.|Ah, there it is.
{84162}{84231}I told Sue I'd take you somewhere|really special for dinner.
{84233}{84288}You're gonna love this place.|Trust me.
{84457}{84534}Now, pick out what you want|of the menu here...
{84536}{84598}and you yell it out|into that box.
{84600}{84653}Two minutes later,|you're scarfing it down...
{84655}{84728}without even|getting out of the car.
{84730}{84783}We have these drive-ins|back home in the cities,
{84785}{84834}but this is|where it all started.
{84836}{84974}So you can eat like a pig|and no one can see you.
{84977}{85025}Clever buggers,|these Yanks, eh?
{85028}{85098}Well, this is why L. A. is famous|all around the world--
{85100}{85145}for its fine cuisine.
{85147}{85194}[ Girl] Welcome to Wendy's.|Can I take your order?
{85196}{85280}Let me handle this.|Good evening, Wendy.
{85282}{85412}There will be four of us|dining in the car this evening.
{85413}{85497}So we're gonna need|four triple burgers with cheese...
{85499}{85536}and four Biggie Fries.
{85537}{85588}So that's four Classic riples...
{85590}{85638}- Uh, wait a minute.|- and four Biggie Fries?
{85640}{85731}Uh, here comes Stan and Harry.
{85733}{85802}Uh, they'll also be|dining with us tonight,
{85804}{85918}so we need...|six triple burgers with cheese...
{85920}{85987}and six Biggie Fries.
{85989}{86095}Okay. Six Classic ripples|with cheese and six Biggie Fries?
{86161}{86243}- You know what I'd really like to do?|- What's that?
{86245}{86321}Go right up on the roof|on one of those skyscrapers.
{86322}{86411}That's easy.|Just find one that's open.
{86638}{86709}S'truth. This is|higher than Ayers Rock.
{86770}{86869}Yeah. Of course, the buildings|in New York are a lot higher.
{86870}{86918}I was there, you know.
{86920}{86976}Old New York.
{86977}{87064}Or as we call it, the "Big Apple. "
{87066}{87136}Big Apple?|Why do you call it that?
{87183}{87253}Well, because|it's really big and, uh--
{87254}{87330}Yeah, but none of those buildings|are as dangerous as this.
{87394}{87415}What do you mean?
{87417}{87472}Well, they don't have|earthquakes in New York.
{87474}{87542}They have 'em here|all the time, right?
{87544}{87602}Yeah.
{87604}{87668}We could have one right now.
{87669}{87716}God!
{87717}{87764}What do you reckon|it'd do to this building?
{87765}{87855}Hey, I wouldn't wanna be up here|if she started shakin', eh?
{87857}{87903}[ Chuckling ]
{87905}{87948}I've seen enough.|You done?
{87950}{88023}Oh, yeah.|No point in hangin' round.
{88153}{88200}This quake-safe?
{88201}{88248}No worries.
{88609}{88750}Oh, mate, I need a drink|after all those 1, 286 stairs.
{88752}{88804}No worries, mate.
{89270}{89328}Didn't work.
{89329}{89415}Well, you gotta wait. There's hundreds|of cars going through...
{89417}{89479}and just us two trying to cross.
{89513}{89572}Yeah?|Now there's 20 of us, eh?
{89573}{89637}Yeah, but you can't do that.|It's illegal.
{89639}{89713}Well, I don't see any cops.
{89715}{89780}Yeah, but they have cameras|at all these intersections, see?
{89782}{89877}If you do anything wrong, they take|your picture and send you a fine.
{89925}{89982}Yeah, but I ain't wearing|a number plate around my neck,
{89984}{90049}so how the hell are they|gonna know who I am, huh?
{90127}{90222}When you landed here,|you showed 'em your passport, right?
{90224}{90274}- Yeah.|- Got your picture in it, dopey.
{90276}{90325}Oh, yeah, right.
{90368}{90416}I wonder|how much they fine you.
{90417}{90483}It all depends on how many times|you push the button.
{90554}{90661}- This looks like us.|- Great. Texas bar. We're in.
{90662}{90716}This could be a bit of fun.
{90717}{90796}These American cowboys|like a good barroom brawl.
{90797}{90853}- ## [Disco ]|- Howdy, boys. Step on in.
{90854}{90901}Howdy, ma'am.
{90964}{91010}- Ma'am.|- Howdy, cowboys.
{91105}{91193}# It's raining men|Hallelujah #
{91195}{91276}Stone the bloody crows!
{91277}{91333}That must've been|one of those poofter bars.
{91334}{91462}Yup. Only I believe|the correct term is "gay homosexual. "
{91464}{91518}That's what they call|their shirt-lifters over here.
{91520}{91608}The only woman there was|the cowgirl at the door.
{91649}{91704}## [ Rap ]
{91758}{91802}Give it up, punk,|or I'll blow you away.
{91804}{91882}- ## [Rap Continues]|- Uh, hang on. I can't hear you.
{91912}{91949}## [Stops]
{91951}{92033}- That's better. Now how can I help you?|- Smart-ass cowboy, huh?
{92035}{92089}- Hand me over your money, man!|- They ain't cowboys.
{92090}{92203}- They're fools dressed up!|- Fools got money too. [ Laughing ]
{92205}{92285}- Give it up or I'll bust a cap in your ass!|- Yeah, hand it over, bitch!
{92312}{92374}Bitch?
{92376}{92460}Son, you have any idea how quick|you have to be to catch a tiger snake?
{92550}{92629}I'm always getting mugged.|I must look rich.
{92630}{92716}It's one of them soft-top cars.|Cave in.
{92763}{92813}- [Punks Yelling]|- [ Horn Honks ]
{92815}{92877}- Ow!|- You know,
{92879}{92940}this must be why they call L. A.|the "City on Wheels. "
{92942}{92963}What do you mean?
{92966}{93025}They don't even get out|of their car to mug you.
{93055}{93145}- Hey!|- [ Groaning] Ow!
{93147}{93236}It's all your fault, homes!|You shouldn't have called him a bitch!
{93346}{93401}Should we call the cops?
{93402}{93521}No point. Over here,|they'd probably end up suing us.
{93522}{93602}Besides, it's not their fault.
{93604}{93652}It's the drugs.
{93654}{93740}I saw all about it|on that Geraldo Rivera.
{93741}{93789}He knows the streets.
{93791}{93845}Let's just get a cup of coffee|and go home.
{93848}{93927}Don't be too hasty|ordering coffee around here.
{93929}{93988}You might not be too happy|with the way they serve it.
{93990}{94039}Trust me.
{94105}{94207}And this is where a big crocodile|almost bit his leg right off.
{94209}{94260}- Whoa!|- Neat!
{94262}{94389}Well, to tell the truth, kids,|it wasn't really that big.
{94416}{94473}No more than 20 feet or so|anyway.
{94474}{94528}[Boy]|Whoa! That's huge!
{94737}{94811}- [ Chittering ]|- Yes, I know.
{94813}{94898}They just don't appreciate|a real artiste. I'd have bit him too.
{94900}{94967}I thought you were fabulous.
{94969}{95026}I don't care what that director said.|He's an idiot.
{95061}{95117}You were really good.
{95118}{95165}- You said black with one sugar, right?|- Oh, yes.
{95166}{95227}- Thanks, mate. Excellent.|- And...
{95229}{95277}I got us a little treat|for our friend here.
{95279}{95337}Oh, great.|That'll hit the spot.
{95338}{95411}- Black and one sugar.|- [ Slurps ]
{95413}{95493}She's a bit grumpy today.
{95494}{95553}Not happy with|the size of her trailer.
{95555}{95604}She wants a big one like Virgil,|but I keep telling her,
{95605}{95669}"Virgil's a lion.|You're only a monkey. "
{95671}{95756}- [ Chittering ]|- Sorry.
{95757}{95805}"Chimpanzee. "
{95807}{95853}Say, have you thought|about changing agents?
{95901}{95979}Diego, you're talking to a chimp.|They don't speak English.
{95981}{96056}Neither did my first wife.
{96057}{96081}Neither did my first wife.
{96109}{96146}Keep moving, Dravos.
{96835}{96918}Don't be stupid!|Mind the painting!
{96985}{97044}[ Muttering ]
{97170}{97217}Just lean it carefully|against the wall for now.
{97218}{97284}- [ Thuds ]|- Carefully!
{97467}{97540}G'day, Phil.|What's happening, mate?
{97542}{97607}Hi, Mick.|The usual continuity nightmare.
{97609}{97663}Right.
{97665}{97757}- What's that mean?|- It means I have to make this set...
{97758}{97848}look exactly like it did|on location in Yugoslavia.
{97890}{97981}Yugoslavia. Is that where|all these paintings come from?
{97982}{98066}Yup. They had them|done there. Dumb.
{98068}{98157}Would've been cheaper here,|and more realistic.
{98159}{98259}Oh, so none of these are valuable.|They're just all copies.
{98261}{98327}Yup, and rather|poor ones at that.
{98329}{98448}And these huge, tacky frames?|For God sakes.
{98451}{98517}Don't they usually cart|the sets and the props...
{98519}{98597}from one country|to another and back again?
{98599}{98681}Maybe in a big-budget international|movie like Mission: Impossible 3.
{98682}{98749}But I haven't seen Tom Cruise|hanging around the set, have you?
{98802}{98862}Tom Cruise.|What's he look like?
{98864}{98938}Like... Tom Cruise.
{98997}{99057}Jeez, Mick, were you|born in a cave?
{99058}{99106}Yeah!|How did you know that?
{99108}{99158}Never mind.
{99213}{99278}Jim, the Van Goghs|are down at the wrong end.
{99281}{99360}See, here they started with|the Gauguins, one above the other.
{99361}{99416}Let's get this right.|We gotta be done in here tonight.
{99417}{99464}They're shooting|in here tomorrow.
{99757}{99813}[ Sniffs ]
{99814}{99870}[Mick ] You see,|you can mix heroin into a plaster,
{99872}{99918}make it any shape you like.
{99920}{100017}So, when I see this guy go nuts 'cause|they bumped the lousy painting,
{100020}{100071}that's when I knew|where the drugs were hidden--
{100073}{100120}molded into the picture frames.
{100121}{100201}Pure heroin, or|as we call it, "smack. "
{100203}{100281}Jeez, Mick, you really do|think like a detective.
{100282}{100371}Yeah, well, it comes sort of|natural to me, you know?
{100373}{100427}- Hey, Mick.|- Ah.
{100429}{100503}That was the police lab.
{100505}{100588}Sorry. The frames are just plaster.|There's no drugs.
{100590}{100637}Oh, bugger it.
{100672}{100726}I was sure|I cracked the case.
{100728}{100803}I don't know. Maybe they're not|smuggling anything.
{100805}{100853}Oh, no. They're sneaking around|with something.
{100854}{100912}I just haven't found it yet.
{100913}{100960}Look, I read about this fella,
{100961}{101044}he used to push|a wheelbarrow full of cow dung...
{101047}{101095}across the border every day.
{101097}{101152}"Manure for the garden, " he'd say.|Went on for months.
{101153}{101224}And the border guards knew|he was smuggling something,
{101225}{101290}so they'd stop him and rake through|that manure with a fine-tooth comb.
{101292}{101359}Never found a thing.
{101361}{101450}Turned out they were right.|He was smuggling something:
{101452}{101507}wheelbarrows.
{101509}{101573}Right under their noses.
{101574}{101683}See, it's there, and I'm just|not seeing it... yet. But I will.
{101717}{101819}Nah. I reckon he was right|the first time. It's drugs.
{101821}{101896}They wouldn't go to all|that trouble for wheelbarrows.
{102179}{102241}Cut! And print.
{102243}{102311}We'll cut when he throws,|so that'll work fine.
{102313}{102359}- All right!|- Well done, Paul.
{102361}{102449}[Assistant Director] Listen, everyone,|we do not burn down the castle now.
{102451}{102516}That will be|a second-unit shot tomorrow.
{102518}{102577}That means everyone goes home early|and has tomorrow off.
{102579}{102649}- Whoo! All right!|- Okay, see you all Friday!
{102650}{102702}First thing!
{103007}{103098}[ Man ] And you've actually seen|these paintings quite recently.
{103100}{103133}Yeah, today.
{103134}{103212}Well, then that makes it easy.|They're fakes.
{103214}{103274}You can tell that|from the photographs?
{103277}{103356}Well, normally, no.|But, you see, these Rembrandts...
{103357}{103422}and this, The Olive Field|by Van Gogh,
{103424}{103472}unfortunately no longer exist.
{103473}{103554}During the bombing|of Belgrade by NATO,
{103556}{103625}the National Art Museum of Serbia|took a direct hit,
{103627}{103707}burned to the ground along with|the originals of these paintings...
{103709}{103819}and possibly the finest collection|of old masters in Eastern Europe.
{103821}{103883}It was a tragedy|for the art world.
{103885}{103984}Ergo, these must be copies, fakes.
{104053}{104136}That, um, Belgrade,|is that in Yugoslavia?
{104173}{104280}- Yeah.|- Where these paintings come from.
{104323}{104384}What if it wasn't|an accidental bombing...
{104386}{104458}and someone removed|the paintings first?
{104460}{104519}Spoils of war?
{104557}{104676}Maybe I should take a look at these.|Could you take me to them?
{104677}{104754}That's probably impossible.
{104756}{104865}But if I could get one of them|and bring it to you and it was real,
{104868}{104916}that means the rest|are probably real, right?
{104919}{105001}You must call me the minute|you find one. I have to see them.
{105004}{105082}- No worries.|- Thank you. Thank you.
{105181}{105260}- Hey, who drew this?|- Pablo Picasso.
{105296}{105387}I'm a drinking man myself,|but I've never been that hammered.
{105577}{105645}This'll be a piece of cake.|I know this lot backwards.
{105685}{105755}- Wait in the car.|- Uh, Mick?
{105785}{105836}I was gonna say, "Be careful, "
{105837}{105933}but I guess that's kind of a dumb thing|to say to someone who hunts crocodiles.
{105935}{105983}No worries.
{106264}{106310}Of course the difference|is obvious here,
{106312}{106401}but on film,|it's a perfect match.
{106402}{106449}- Isn't it?|- All right, we have the paintings.
{106450}{106541}Now must we continue with|this stupid movie business bullshit?
{106542}{106589}You really don't get it, do you?
{106590}{106677}God is in the details.
{106679}{106753}These came into the country as|film props. Anyone wants to see them--
{106755}{106804}"Sorry. We burned them.
{106806}{106892}Want proof? Go see the movie. "
{106894}{106986}Dead end. Brilliant.
{107302}{107372}Carl, we need your help.
{107535}{107616}Carl, that painting should be covered.
{107617}{107678}I'll be with you in a moment.
{107680}{107757}- Then who the hell is that?|- [Milos] Stop him!
{107759}{107818}After him! Quickly!
{107821}{107895}Shoot low!|Don't hit the painting!
{107897}{107957}After him!|Seal off the lot!
{107960}{108026}- Quick! Hold this! Thanks.|- What?
{109004}{109061}He ran in here.|Dravos followed him.
{109062}{109174}Cover all the exits.|Go in and help Dravos flush him out.
{109213}{109292}[ Whispering ] Shh. I know, I know.|Mick said to wait here.
{109293}{109347}It's his bust, right?
{109349}{109410}I know. I was just looking.
{109413}{109484}How'd you get here anyway?|Who's looking after Mikey?
{109487}{109547}Miss Mathis,|his teacher from school.
{109549}{109596}I followed you in her car.
{110621}{110683}Oh. I'll just keep you on hold.
{110721}{110757}Ah.
{110830}{110897}[ Screams ]
{111063}{111145}Keep you on hold. Ha!|I just come out with them.
{111195}{111266}- Who is this man? How does he--|- I think he's the monkey guy.
{111268}{111345}Mick, the guy that trains|the monkey. Same hat.
{111347}{111434}How would the monkey guy|know about the paintings?
{111436}{111502}Is he alone?|You better hope he's still alive.
{111504}{111556}Get in there.
{111557}{111614}[Man On Walkie-talkie. ]|We're entering stage four.
{111616}{111680}- We'll flush him your way.|- Roger that.
{111987}{112035}[Bell Ringing]
{113225}{113279}[ Laughs ]
{113356}{113447}[ Moos ]
{113449}{113502}- [ Farts ]|- Oh!
{113944}{114003}Shoot low.|We need him alive.
{114815}{114871}[ Whistles ]
{114873}{114932}- Watch out...|- [ Screaming ]
{115028}{115076}for the wall.
{115290}{115332}He's gone to the jungle set.
{115333}{115393}There's only one way|in and out of there.
{115394}{115467}- I'm on it.|- Cover the gate till we get there.
{115619}{115687}[Leaves Rustling]
{116929}{117016}Hey! Hey! Hey! Hey!
{117093}{117140}High five.
{117142}{117216}[Man On Walkie-talkie ] Stan, copy.|Boss said don't go in there alone.
{117218}{117287}- Stan? Stan?|- Too late, mate.
{117289}{117318}Stan!
{117828}{117884}Oh, shit.
{117885}{117963}Did it, um--
{117965}{118089}I- It... missed, I think.
{118133}{118182}I hope.
{118588}{118635}Hi, Mick.
{118705}{118750}I know you're still here.
{118795}{118879}Why don't we stop|playing this silly game?
{118924}{119008}You can come out and...
{119009}{119079}join your friends.
{119081}{119168}I have no more patience for this!
{119169}{119278}[Mick]|Okay, you win. I'm comin' out.
{119397}{119492}Just don't make|any sudden moves.
{119493}{119559}You don't have to be so formal.|We're all friends.
{119561}{119614}You can... lower your hands.
{119701}{119748}I can't really lower this one.
{119749}{119824}- And why is that?|- 'Cause if I put this arm down...
{119825}{119872}and break eye contact,
{119873}{119931}he might come down here|and tear you apart.
{119933}{120007}- Who?|- Fella who lives in there.
{120143}{120208}Look. Up on the rock.
{120210}{120295}[ Growling ]
{120297}{120403}Are you nuts?|Can't kill a lion with a. 38pistol.
{120405}{120465}- You'll just piss him off.|- [ Growling ]
{120467}{120561}If you shoot anyone,|they better not bleed.
{120563}{120616}Lions go berserk|when they smell blood.
{120681}{120759}If I was you, I'd back up slowly|into that cage.
{120922}{120972}[ Gulps, Clears Throat ]
{120975}{121062}Uh, yeah.|Surely, that's a...
{121064}{121109}tame lion.
{121111}{121182}Yeah. You could be right.
{121184}{121264}[ Roaring ]
{121327}{121397}I shoot you. You bleed.
{121398}{121505}- I take my chances.|- But he's not your problem.
{121507}{121604}- It's his missus I'm worried about.|- [ Growling ]
{121654}{121737}I can't handle her.
{121740}{121822}She's got PMS, I think.|Can see it in her eyes.
{121877}{121961}Anyway, you do|what you have to do.
{121963}{122012}I'm getting in the cage...
{122014}{122085}before his mother-in-law|comes down.
{122087}{122165}- No! No!|- [ Roaring ]
{122166}{122254}- Open the door! Open the door now!|- Give me the gun.
{122330}{122389}You held a gun to my wife's head.
{122390}{122457}- Huh?|- That's unforgivable.
{122459}{122514}- I'm gonna help you lose some weight.|- How?
{122517}{122595}Virgil's gonna come down here and|bite a big chunk out of your fat ass.
{122597}{122687}- [ Whimpering ]|- Virgil, lunch!
{122816}{122881}- [ Roars ]|- Sit!
{123123}{123151}[ Roars ]
{123208}{123239}Ah.
{123241}{123355}If you touch me, I will sue you|for every cent you've got.
{123357}{123429}Ha! Well, that sounds fair.
{123517}{123571}Hey, that's about 40 bucks.
{123573}{123637}[ Laughs ]|It's a fair deal.
{123639}{123688}Bargain.
{123690}{123737}And how are you, miss?
{123738}{123798}- What the hell were you doing in here?|- Well, I had to.
{123800}{123829}My cell phone went dead,
{123831}{123898}and I had to come in here|to find a phone to call 911.
{123900}{123984}You're clever, Sue. I never|would've thought of that.
{123985}{124057}Yeah, well, that's because|she's a Dundee.
{124094}{124157}Or she ought to be.
{124160}{124273}Uh, Jacko, keep an eye on|the goons and, uh, block your ears.
{124275}{124360}- What?|- Block your ears. Private talk.
{124361}{124424}No worries, mate.
{124453}{124526}Uh, I have to tell you this.
{124559}{124635}I was just really scared|for the first time in my life.
{124637}{124724}Well, that's okay.|Most people are frightened of lions.
{124725}{124797}No, not the lions.|They're just hungry.
{124798}{124846}It's when I saw that goon|with a gun at your head.
{124873}{124969}That's when I realized|how much I, uh--
{125071}{125122}You know, um--
{125124}{125182}Will you marry me?
{125226}{125320}Well, you do rush into things,|don't you, Mick?
{125321}{125376}Are you sure it's not|just the romantic setting?
{125468}{125526}Local experts say the value|of the recovered art...
{125528}{125607}could run as high|as $300 million.
{125609}{125688}For the very latest, let's go live|to Marta Waller at the scene. Marta?
{125690}{125748}Thanks, Hal. Right now|the police are taking...
{125749}{125824}these priceless paintings|into protective custody.
{125827}{125902}The woman behind me talking to|the detective is Ms. Sue Charleton,
{125904}{125928}the Newsday reporter...
{125930}{126030}who led detectives to the cache|of stolen masterpieces.
{126193}{126229}However, earlier tonight,
{126231}{126323}he did tell me he is, in fact,|a known expert in the art world.
{126325}{126377}Isn't that the guy who had|the skunk on the freeway?
{126379}{126470}- [ Man Whispers ] Hey, Hal!|- We'll have more as the story unfolds.
{126472}{126519}Right now|let's go to Malibu...
{126521}{126604}where last night's downpour|of almost a quarter inch of rain...
{126606}{126690}resulted in disastrous flooding|and massive mud slides...
{126693}{126739}along the Pacific Coast Highway.
{126824}{126902}[ Man ]|Sue, do you accept this larrikin...
{126904}{126957}as your wedded husband?
{126959}{127007}- I do.|- Mick,
{127009}{127086}do you accept this lovely lady|as your wedded wife?
{127149}{127207}No worries.
{127209}{127307}Fair enough.|I now pronounce you...
{127309}{127357}husband and wife.
{127359}{127427}[ Cheers And Applause ]
{127517}{127573}- Good on ya, Mick.|- All right!
{127853}{127924}It's official now, mate.|You're Mick Dundee II.
{127926}{128005}- Cool.|- Now I guess we'll wait and see...
{128006}{128096}whether you turn out to be|another Crocodile Dundee...
{128097}{128169}or Michael Dundee,|newspaper tycoon.
{128171}{128228}Oh, that's a no-brainer, Dad.
{128229}{128289}I'm gonna be|Crocodile Dundee,
{128291}{128366}hunter and rich owner|of a big newspaper.
{128368}{128441}I didn't raise a dumbbell.
{128443}{128509}Put this on for the photos.
{128511}{128598}- What for?|- You look like a dork in that suit.
{128600}{128677}- No, I don't.|- You should look like Crocodile Dundee.
{128846}{128953}No, I think my crocodile|huntin' days are over.
{128954}{129082}From here on in, it's...|"Mick Dundee, Private Eye. "
{129145}{129207}Nah. I'm kiddin'.
{129249}{129350}[ Women Yelling ]
{129472}{129532}##
{129534}{129594}# I come from a land|down under #
{129645}{129705}# The beer does flow|and men chunder #
{129753}{129812}# Can't you hear|can't you hear that thunder #
{129850}{129965}# You better run|You better take cover, yeah #
{129967}{130020}# raveling in|a fried-out combie #
{130078}{130145}# On a hippie trail|Head full of zombie #
{130186}{130237}# I met a strange lady #
{130239}{130297}# She made me nervous #
{130299}{130376}# She took me in|and gave me breakfast #
{130377}{130460}# She said do you come|from a land down under #
{130513}{130576}# Where women glow|and men plunder #
{130622}{130678}# Can 't you hear|can 't you hear the thunder #
{130720}{130828}# You better run|You better take cover, yeah #
{130948}{131006}# Buying bread|from a man in Brussels #
{131037}{131124}# He was six foot four|and full of muscles #
{131165}{131264}# I said do you speak|my language, brother #
{131265}{131358}# He just smiled and gave me|a Vegemite sandwich #
{131360}{131442}# He said I come from|a land down under #
{131495}{131556}# Where beer does flow|and men chunder #
{131601}{131664}# Can 't you hear|can 't you hear the thunder #
{131705}{131814}# You better run|You better take cover, yeah #
{131927}{131988}# Lying in a den in Bombay #
{132042}{132109}# With a slack jaw|and not a lot to say #
{132152}{132218}# I said to the man|Are you trying to tempt me #
{132258}{132340}# Because I come from|the land of plenty #
