---
title: "The NeverEnding Story II: The Next Chapter"

alternative_titles:
- "Бесконечная история 2: Новая глава"
- "La storia infinita 2"
- "Die unendliche Geschichte 2: Auf der Suche nach Phantásien"

imdb_id: "tt0100240"
tmdb_id: "34636"
year: "1990"
