---
title: "Commando"

alternative_titles:
- "Commando - A One Man Army"

filename: "Commando-2013-Hindi-Hon3y.srt"
language: "en"
imdb_id: "tt2658126"
tmdb_id: "185640"
year: "2013"
format: "srt"

matches:
- filename: "Commando-2013-Hindi-Hon3y.mp4"
  hash: "41c3939951033bbb"
  filesize: "942946979"
