---
title: "Pirates of the Caribbean: The Curse of the Black Pearl"

alternative_titles:
- Fluch der Karibik
- "Пираты Карибского моря: Проклятие Чёрной жемчужины"

filename: Pirates Of The Caribbean - The Curse Of The Black Pearl (2003).srt
language: en
imdb_id: tt0325980
tmdb_id: 22
year: 2003
format: srt

matches:
- filename: Pirates Of The Caribbean - The Curse Of The Black Pearl (2003).avi
  hash: 5290b8ab66d4dbcb
  filesize: 944850944
