---
title: "Pirates of the Caribbean: The Curse of the Black Pearl"

alternative_titles:
- "Fluch der Karibik"
- "Пираты Карибского моря: Проклятие Чёрной жемчужины"

imdb_id: "tt0325980"
tmdb_id: "22"
year: "2003"
