---
title: "The Curious Case of Benjamin Button"

alternative_titles:
- "Загадочная история Бенджамина Баттона"
- "Il curioso caso di Benjamin Button"
- "Der seltsame Fall des Benjamin Button"

imdb_id: "tt0421715"
tmdb_id: "4922"
year: "2008"
