---
title: "As Tears Go By"

original_title: "Wang Jiao ka men"

alternative_titles:
- "Carmen of the Streets"
- "Conflito Mortal"
- "El fluir de las lágrimas"
- "Ahogy peregnek a könnyek"
- "Fatal Checkout"
- "Yeolheol nama"
- "Kiedy lzy przemina"
- "Ao Sabor da Ambição"
- "Пока не высохнут слезы"
- "Ölüm Hesabi"
- "Vuong Giac Khai Mon"

imdb_id: "tt0096461"
tmdb_id: "24163"
year: "1988"

