---
title: "The Five People You Meet in Heaven"

alternative_titles:
- "Die fünf Menschen, die dir im Himmel begegnen"
- "Куда приводят сны"
- "As Cinco Pessoas que Você Encontra no Céu"

imdb_id: "tt0400435"
tmdb_id: "30698"
year: "2004"
