---
title: "A Dangerous Method"

alternative_titles:
- "Eine dunkle Begierde"
- "Опасный метод"
- "Un método peligroso"

filename: "A.Dangerous.Method.2011.480p.BRRip.XviD.AC3-BKZ.srt"
language: "en"
imdb_id: "tt1571222"
tmdb_id: "48231"
year: "2011"
format: "srt"

matches:
- filename: "A.Dangerous.Method.2011.480p.BRRip.XviD.AC3-BKZ.avi"
  hash: "3ea37726543b32b4"
  filesize: "1562307632"
