---
title: "Pirates of the Caribbean: Dead Man's Chest"

alternative_titles:
- "Fluch der Karibik 2"
- "Пираты Карибского моря: Сундук мертвеца"
- "Karayip korsanlari - Ölü adamin sandigi"

imdb_id: "tt0383574"
tmdb_id: "58"
year: "2006"
