---
title: Pirates of the Caribbean: Dead Man's Chest

alternative_titles:
- Fluch der Karibik 2
- Пираты Карибского моря: Сундук мертвеца
- Karayip korsanlari - Ölü adamin sandigi

filename: Pirates Of The Caribbean - Dead Man's Chest (2006).srt
language: en
imdb_id: tt0383574
tmdb_id: 58
year: 2006
format: srt

matches:
- filename: Pirates Of The Caribbean - Dead Man's Chest (2006).avi
  hash: a45c97990a0d4629
  filesize: 944136192
