---
title: "Memoirs of an Invisible Man"

alternative_titles:
- "Исповедь невидимки"
- "Jagd auf einen Unsichtbaren"
- "Díario de un hombre invisible"

imdb_id: "tt0104850"
tmdb_id: "2687"
year: "1992"
