---
title: "Embrace of the Serpent"

original_title: "El abrazo de la serpiente"

alternative_titles:
- "Объятия змея"
- "Zagrljaj zmije"
- "L'étreinte du serpent"
- "Slangens favntag"
- "Der Schamane und die Schlange"
- "O Abraço da Serpente"

imdb_id: "tt4285496"
tmdb_id: "336808"
year: "2015"
