---
title: "Swordsman II"

original_title: "Xiao ao jiang hu: dong fang bu bai"

alternative_titles:
- "The Legend of the Swordsman"
- "China Swordsman"

imdb_id: "tt0103295"
tmdb_id: "18672"
year: "1992"
