---
title: "The Hobbit: The Desolation of Smaug"

alternative_titles:
- "Der Hobbit - Smaugs Einöde"
- "Хоббит: Пустошь Смауга"
- "Hobit: Smaugova pustoš"

imdb_id: "tt1170358"
tmdb_id: "57158"
year: "2013"
