---
title: "Desk Set"

alternative_titles:
- "Eine Frau, die alles weiß"
- "Eine Frau, die alles kennt"
- "Bürodaki sevgili"
- "Кабинетный гарнитур"
- "Une femme de tête"

imdb_id: "tt0050307"
tmdb_id: "24203"
year: "1957"
