---
title: "Fletch Lives"

alternative_titles:
- "Fletch - Der Tausendsassa"
- "Fletch 2 - Der Troublemaker kehrt zurück"
- "Флетч жив"
- "Autant en emporte Fletch!"

imdb_id: "tt0097366"
tmdb_id: "14628"
year: "1989"
