---
title: "Psycho-Pass: The Movie"

original_title: "Gekijouban Psycho-Pass"

alternative_titles:
- "Psycho-Pass Movie"
- "Psycho-Pass. La película"
- "Психопаспорт"

imdb_id: "tt4219130"
tmdb_id: "296917"
year: "2015"
