---
title: Psycho-Pass: The Movie

original_title: Gekijouban Psycho-Pass

alternative_titles:
- Psycho-Pass Movie
- Psycho-Pass. La película
- Психопаспорт

filename: Psycho-Pass.The.Movie.2015.720p.BRRip.x264.Japanese.AAC-ETRG.srt
language: en
imdb_id: tt4219130
tmdb_id: 296917
year: 2015
format: srt

matches:
- filename: Psycho-Pass.The.Movie.2015.720p.BRRip.x264.Japanese.AAC-ETRG.mp4
  hash: 740d23d1d7594da0
  filesize: 936785202
