---
title: "Blue Gender: The Warrior"

filename: Blue_Gender-The_Warrior.srt
language: en
imdb_id: tt1345450
tmdb_id: 37326
year: 2002
format: srt

matches:
- filename: Blue_Gender-The_Warrior.avi
  hash: e49ae27b70acd0f6
  filesize: 707278848
