---
title: "Once Upon a Time in China II "

original_title: "Wong Fei Hung II: Nam yee tung chi keung"

alternative_titles:
- "Once Upon a Time in China 2"
- "Es war einmal in China 2"
- "Однажды в Китае II"

imdb_id: "tt0105839"
tmdb_id: "10618"
year: "1992"
