---
title: "The Man Who Shot Liberty Valance"

alternative_titles:
- "Der Mann der Liberty Valance erschoss"
- "Человек, который застрелил Либерти Вэланса"
- "L'uomo che uccise Liberty Valance"

imdb_id: "tt0056217"
tmdb_id: "11697"
year: "1962"
