---
title: "Spring, Summer, Fall, Winter... and Spring"

original_title: "Bom yeoreum gaeul gyeoul geurigo bom"

alternative_titles:
- "Frühling, Sommer, Herbst, Winter... und Frühling"
- "Printemps, été, automne, hiver... et printemps"
- "Весна, лето, осень, зима... и снова весна"

imdb_id: "tt0374546"
tmdb_id: "113"
year: "2003"
