---
title: "Gentlemen Prefer Blondes"

alternative_titles:
- "Blondinen bevorzugt"
- "Джентльмены предпочитают блондинок"
- "Gli uomini preferiscono le bionde"

imdb_id: "tt0045810"
tmdb_id: "759"
year: "1953"
