---
title: "New Dragon Gate Inn"

original_title: "Sun lung moon hak chan"

alternative_titles:
- "Xin long men ke zhan"
- "Таверна Дракона"
- "L'auberge du dragon"
- "Dragon Inn"
- "New Dragon Inn"

imdb_id: "tt0105859"
tmdb_id: "40213"
year: "1992"
