---
title: Schizo

original_title: Shiza

alternative_titles:
- Schiza - Fifty/Fifty
- Skiso
- Fifty-Fifty
- Шиzа

filename: Shiza.srt
language: en
imdb_id: tt0406216
tmdb_id: 47200
year: 2004
format: srt

matches:
- filename: Shiza.avi
  hash: 8b7d5fca75ca6d56
  filesize: 734343168
