---
title: "Upstream Color"

alternative_titles:
- "Upstream Colour"
- "Cores do Destino"
- "Kontra sto revma"
- "Feltörő színek"
- "Los colores del destino"
- "Color a contracorriente"
- "Примесь"
- "Gizli Kimya"

imdb_id: "tt2084989"
tmdb_id: "145197"
year: "2013"
