---
title: "The Good, the Bad and the Ugly"

original_title: "Il buono, il brutto, il cattivo"

alternative_titles:
- "Zwei glorreiche Halunken"
- "Хороший, плохой, злой"
- "Lo bueno, lo malo y lo feo"

imdb_id: "tt0060196"
tmdb_id: "429"
year: "1966"
