---
title: "Nick and Norah's Infinite Playlist"

alternative_titles:
- "Nick und Norah - Soundtrack einer Nacht"
- "Будь моим парнем на пять минут"
- "Nick y Nora, una noche de música y amor"

imdb_id: "tt0981227"
tmdb_id: "12182"
year: "2008"
