---
title: "It's Kind of a Funny Story"

alternative_titles:
- "Это очень забавная история"
- "Eine echt verrückte Story"
- "Se Enlouquecer, Não se Apaixone"

imdb_id: "tt0804497"
tmdb_id: "43923"
year: "2010"
