---
title: "Lethal Weapon 2"

filename: "Lethal Weapon 2 - Director's Cut (1989).srt"
language: "en"
imdb_id: "tt0097733"
tmdb_id: "942"
year: "1989"
format: "srt"

matches:
- filename: "Lethal Weapon 2 - Director's Cut (1989).avi"
  hash: "14b72e9f7cc9d314"
  filesize: "735113216"
