---
title: "Between Calmness and Passion"

original_title: "Reisei to jônetsu no aida"

alternative_titles:
- "Between Calm and Passion"
- "Calmi cuori appassionati"
- "Jing leng yu re qing zhi jian"

imdb_id: "tt0291753"
tmdb_id: "33346"
year: "2001"
