---
title: "Big Trouble in Little China"

alternative_titles:
- "Большой переполох в маленьком Китае"

filename: "Big.Trouble.In.Little.China.1986.720p.BluRay.x264-x0r[SS].srt"
language: "en"
imdb_id: "tt0090728"
tmdb_id: "6978"
year: "1986"
format: "srt"

matches:
- filename: "Big.Trouble.In.Little.China.1986.720p.BluRay.x264-x0r[SS].mkv"
  hash: "f2c98f9fb5926bcd"
  filesize: "2110263664"
