---
title: "Once Upon a Time in Mexico"

alternative_titles:
- "Однажды в Мексике: Отчаянный 2"
- "Irgendwann in Mexico"
- "Il était une fois au Mexique - Desperado 2"

imdb_id: "tt0285823"
tmdb_id: "1428"
year: "2003"
