---
title: "Beyond the Black Rainbow"

alternative_titles:
- "По ту сторону черной радуги"
- "Za czarna tecza"
- "Po drugiej stronie czarnej teczy"
- "Além do Arco-Íris Negro"

imdb_id: "tt1534085"
tmdb_id: "50037"
year: "2010"
