---
title: "The Lord of the Rings: The Two Towers"

alternative_titles:
- "Der Herr der Ringe - Die zwei Türme"
- "Властелин колец: Две крепости"
- "Il Signore degli Anelli - Le due torri"

imdb_id: "tt0167261"
tmdb_id: "121"
year: "2002"
