---
title: "Trail of the Pink Panther"

alternative_titles:
- "Der rosarote Panther wird gejagt"
- "След Розовой Пантеры"
- "A Trilha da Pantera Cor-de-Rosa"

imdb_id: "tt0084814"
tmdb_id: "9699"
year: "1982"
