---
title: "Pirates of the Caribbean: At World's End"

alternative_titles:
- "Fluch der Karibik - Am Ende der Welt"
- "Пираты Карибского моря: На краю света"
- "Pirati dei Caraibi - Ai confini del mondo"

imdb_id: "tt0449088"
tmdb_id: "285"
year: "2007"
