{2333}{2366}My life fades...
{2397}{2440}...the vision dims.
{2457}{2513}All that remains are memories.
{2553}{2610}I remember...a time of chaos...
{2665}{2728}...ruined dreams...this wasted land.
{2777}{2853}But most of all,|I remember the Road Warrior...
{2897}{2947}...the man we called Max.
{2974}{3071}To understand who he was,|you have to go back to another time...
{3089}{3165}...when the world was powered|by the black fuel...
{3170}{3263}...and the deserts sprouted great cities|of pipe and steel.
{3332}{3378}Gone now...swept away.
{3414}{3518}For reasons long forgotten,|two mighty warrior tribes went to war...
{3532}{3614}...and touched off a blaze|which engulfed them all.
{3626}{3722}Without fuel they were nothing.|They'd built a house of straw.
{3738}{3813}The thundering machines sputtered|and stopped.
{3886}{3966}Their leaders talked...and talked...|and talked...
{4070}{4139}...but nothing could stem the avalanche.
{4171}{4243}Their world crumbled...|the cities exploded.
{4303}{4353}A whirlwind of looting...
{4368}{4416}...a firestorm of fear.
{4446}{4496}Men began to feed on men.
{4555}{4627}On the roads it was a white-line nightmare.
{4652}{4716}Only those mobile enough to scavenge...
{4723}{4794}...brutal enough to pillage would survive.
{4811}{4873}The gangs took over the highways...
{4889}{4959}...ready to wage war for a tank of juice.
{5003}{5063}And in this maelstrom of decay...
{5083}{5152}...ordinary men were battered|and smashed.
{5163}{5201}Men like Max...
{5219}{5263}...the warrior Max.
{5332}{5408}In the roar of an engine,|he lost everything...
{5540}{5596}...and became a shell of a man...
{5602}{5659}...a burnt out, desolate man...
{5679}{5750}...a man haunted by the demons|of his past.
{5801}{5871}A man who wandered out|into the wasteland.
{5927}{5999}And it was here...in this blighted place...
{6088}{6148}...that he learned to live again.
{15335}{15397}Don't hurt the snake! Put it down...
{15413}{15463}...gently, gently...nice.
{15497}{15533}Now the iron.
{15607}{15638}The gun.
{15667}{15717}Down, down. Turn around.
{16049}{16123}Looks like I've got myself|some gasoline, eh?
{16137}{16169}V8? Eh?
{16186}{16256}Booby-trapped.|Touch those tanks and boom!
{16462}{16507}Booby-trap! Back up!
{16569}{16626}Oh, you crafty little man, you!
{16644}{16695}You're quick...very quick.
{16749}{16832}Never seen a man beat the snake before.|Who are you?
{16897}{16958}Reflexes...that's what you've got.
{17024}{17069}Me...l've got brains.
{17247}{17298}A fella...a quick fella...
{17325}{17427}...might have a weapon under there.|l'd have to pin his head to the panel.
{17854}{17902}Don't play me the fool!
{18059}{18139}Gas! Fuel! Gasoline!|Thousands of gallons of it!
{18149}{18196}-As much as you want!|-Where? Where?
{18198}{18278}20 miles from here!|Pumping it, they are! Refining!
{18312}{18363}-A huge tanker full.|-Crap!
{18376}{18413}No, it's true!
{18422}{18502}lt's not self-service, no.|lt's too hard for me...
{18510}{18561}...but a man of your ingenuity--
{18563}{18586}Where?
{18606}{18667}Kill me and you'll never find out!
{19142}{19175}Good dog.
{19191}{19221}Nice doggy, eh?
{20029}{20071}Well, there it is.
{20188}{20237}Four days I was up here.
{20248}{20331}Me and the snakes...|playing mah-jong, taking tea...
{20370}{20419}...watching, thinking...
{20440}{20514}...how was I going to get in|and get the gas?
{20552}{20604}Day and night it's pumping.
{20685}{20721}Fuel to burn.
{20746}{20824}They've got the lot:|power, lights, you name it.
{20856}{20928}You can bet your life they mean to keep it.
{20948}{20996}Thirty of them in there.
{21000}{21055}Arrows, flame-throwers, guns!
{21080}{21147}No place for man or reptile, l thought.
{21181}{21232}Then this trash arrived...
{21257}{21305}...as moths to a flame.
{21309}{21370}Round and round, attack, attack...
{21393}{21475}...like angry ants,|mad with the smell of gasoline.
{21867}{21937}In the tanker, that's where they keep it.
{21973}{22043}Thousands of gallons.|As much as you want.
{22101}{22178}lf anyone's gonna get in there,|it's gonna be you.
{22182}{22239}Me...l'm gonna feed the snakes.
{22350}{22434}A man lives by his word, l reckon.|l've kept mine, eh?
{22666}{22740}We had a deal. l show you the gas|and you let me go, right?
{22742}{22784}The arrangement was l wouldn't kill you.
{22786}{22834}After all l've done for you--
{22848}{22912}l reckon you got a bargain, don't you?
{23587}{23638}Attack, my vermin, attack!
{24245}{24331}Onward! Bring me the fuel.|For the glory of Humungus.
{24336}{24394}For the great glory of Humungus.
{24508}{24560}Smegma crazies to the left!
{24626}{24696}The gate! Gayboy berserkers to the gate!
{24852}{24890}I am your Lord.
{24988}{25039}Attack, my vermin, attack!
{34797}{34855}Thank you, thank you, thank you!
{34871}{34902}Save it.
{34915}{34972}l'm just here for the gasoline.
{35142}{35184}As much as you like.
{35188}{35237}Just take me back there.
{36360}{36422}Show your weapons and come forward!
{36527}{36557}Steady now!
{36610}{36652}Take it real easy!
{36689}{36735}That's as far as you go!
{36751}{36786}Turn around!
{36811}{36867}Nathan! Nathan! lt's Nathan!
{36893}{36926}Lose them!
{37003}{37040}Open the gate!
{37164}{37221}Hurry up with that damned stretcher!
{37257}{37333}Hey, that's fine, that's fine.|Just stay there.
{37343}{37388}Cover him, cover him!
{37443}{37487}Come on! Quick, quick!
{37507}{37549}Oh, what a waste!
{37576}{37613}Watch his leg!
{37688}{37732}You and your handiwork!
{37741}{37784}He didn't stand a chance!
{37788}{37870}l warned him! You all heard me!|''Madness,'' l said.
{37884}{37947}''We can escape. Take our gas,'' he said.
{38212}{38253}Get that machine inside!
{38272}{38318}Close the damned gate!
{38803}{38838}Who are you?
{38861}{38913}How did you get through out there?
{38917}{38987}Look, l want some answers.|Where did you find him?
{38997}{39081}Two or three miles down the road|left for dead. We had a deal.
{39083}{39139}There were three other vehicles.|Did you see them?
{39141}{39203}They're heading to the southwest|in heaps of trouble.
{39205}{39255}He said if l brought him back|you'd give me some gas.
{39257}{39341}-Now there's not much time.|-There was a woman in the car.
{39362}{39390}She's dead.
{39434}{39471}-What did they do?|-lt was quick.
{39473}{39536}l just want my gas|and l want to get out of here.
{39538}{39604}For all we know he's one of them!|Give him nothing!
{39606}{39648}She's right, he's a parasite!
{39650}{39717}Trading in human flesh! Mercenary trash!
{39748}{39809}-We had an arrangement.|-What do you mean?
{39814}{39859}You talk to this man.
{39895}{39951}Try something! Try something!
{40275}{40339}lf you had a contract, it was with him.
{40343}{40385}And it died with him.
{40389}{40427}Get rid of him!
{40445}{40473}Left!
{40653}{40736}Got to hand it to you, treasure!|The last of the V8 lnterceptors!
{40738}{40781}A piece of history!
{40817}{40874}Would have been a shame to blow it up.
{41218}{41304}Here they come! Close the gates!|They're coming back!
{42986}{43046}Hold your fire! He comes in peace!
{43094}{43155}For Christ's sake, hold your fire!
{44472}{44526}Greetings from The Humungus!
{44544}{44586}The Lord Humungus!
{44602}{44657}The Warrior of the Wasteland!
{44716}{44776}The Ayatollah of Rock and Roller!
{44871}{44922}I am gravely disappointed.
{44939}{45014}Again you have made me unleash my dogs|of war.
{45027}{45099}Look at what remains|ofyour gallant scouts.
{45131}{45186}Why? Because you're selfish!
{45215}{45257}You hoard your gasoline.
{45284}{45328}Don't listen to him!
{45341}{45390}Now, my prisoners say...
{45397}{45473}...you plan to take your gasoline|out of the Wasteland.
{45491}{45570}You sent them out this morning|to find a vehicle.
{45583}{45658}A rig big enough to haul|that fat tank of gas.
{45703}{45744}What a puny plan!
{45757}{45797}Look around you.
{45850}{45896}This is the Valley of Death.
{45906}{45933}See!
{45956}{46038}Nothing can escape!|The Humungus rules the Wasteland!
{46050}{46105}Give them nothing! Blow it up!
{46188}{46242}Humungus will not be defied!
{46737}{46770}Wez! Wez!
{46995}{47038}l've got it! l've got it!
{47371}{47427}Quiet! Quiet! No more games!
{47475}{47512}No more games!
{47532}{47576}We're here for a purpose.
{47584}{47630}We come with an offer.
{47713}{47755}No! No more talk!
{47798}{47841}We go in! We kill!
{47855}{47895}We'll kill them!
{48347}{48387}Be still my dog of war!
{48401}{48447}l understand your pain.
{48451}{48534}We've all lost someone we love.|But we do it my way!
{48548}{48583}Losers wait!
{48602}{48642}We do it my way!
{48657}{48732}Fear is our ally...the gasoline will be ours.
{48783}{48844}Then, you shall have your revenge.
{48975}{49012}Take him away!
{49364}{49442}There has been too much violence,|too much pain.
{49474}{49525}None here are without sin.
{49556}{49609}But I have an honorable compromise.
{49630}{49668}Just walk away.
{49683}{49718}Give me the pump...
{49733}{49769}...the oil...
{49777}{49812}...the gasoline...
{49825}{49906}...and the whole compound,|and I'll spare your lives.
{49928}{50026}Just walk away. I will give you|safe passage in the Wasteland.
{50047}{50133}Just walk away and there will be an end|to the horror.
{50268}{50312}I await your answer.
{50321}{50379}You have one full day to decide.
{51036}{51082}We'll never walk away!
{51113}{51142}Never!
{51637}{51704}You heard what he said!|lt sounds reasonable!
{51727}{51772}We don't have to die!
{51788}{51836}All we have to do is walk away!
{51838}{51876}No! We've worked too hard!
{51878}{51982}lt's simple! All we do is change the fuel|and this junkyard for our lives!
{51985}{52045}Look, if we walk out there,|they'll slaughter us!
{52047}{52127}They'll set us loose|and then cut us down like pigs!
{52130}{52167}Don't listen to them!
{52171}{52217}All right, this is it!
{52231}{52283}l'll talk to this Humungus!
{52320}{52369}He's a reasonable man...
{52392}{52439}...open to negotiation.
{52451}{52517}He promised us safe passage!|He gave his word!
{52525}{52577}And let us suppose he keeps it...
{52592}{52682}...and we walk away from here|with our lives. What then?
{54357}{54392}But remember!
{54396}{54481}Remember one thing:|That is more than just a tanker of gas.
{54485}{54583}That is our lifeline to a place|beyond that vermin on machines.
{54607}{54653}That's 2,000 miles from here!
{54678}{54750}How do you expect us to get it there?|Drag it?
{54754}{54823}lf we have to, yes! There's always a way!
{54846}{54889}But the first step:
{54915}{54955}Defend the fuel.
{54983}{55012}Words!
{55031}{55065}Just words!
{55080}{55123}You'd die for a pipe dream!
{55131}{55180}We fight for a belief! l stay!
{55408}{55466}l wish it could have worked, Pappagallo.
{55468}{55525}You can't expect to compete with that.
{55538}{55625}Every day we get weaker|while they get stronger. lt's finished!
{55637}{55670}l'm sorry.
{55822}{55913}Two days ago l saw a vehicle|that could haul that tanker.
{55948}{56024}lf you wanna get out of here...|you talk to me.
{56178}{56228}Okay, so that's my offer.
{56235}{56287}l deliver a rig big enough|to haul that tanker...
{56289}{56376}...you give me back my vehicle|and as much juice as l can carry.
{56382}{56439}We lost eight good people this morning.
{56490}{56536}What's he got in mind?
{56550}{56622}Now, to do the job|l need five gallons of diesel...
{56626}{56678}...and some high-octane gasoline.
{56763}{56811}Think of it as a down payment.
{56814}{56878}And that's the last we'll ever see of him.
{56883}{56936}He has to come back for his wheels.
{56941}{56983}What have we got to lose?
{57040}{57070}You've got yourself a deal.
{57673}{57743}My vehicle and all the juice l can carry.
{58964}{59000}Come on, dog.
{63176}{63251}You know what l miss most of all?|Clean women.
{63277}{63325}Nail polish, perfume...
{63365}{63437}...the smell of bicycle seats, cocktails...
{63468}{63507}-Shut up!|-...desserts.
{63529}{63584}Lingerie. Remember lingerie?
{63881}{63942}l knew it! l knew it would work!
{63949}{64020}Lethal! Lethal these snakes. Born killers.
{64113}{64189}lt's my snake! l trained it.|l'm gonna eat it!
{64194}{64254}So find your own! Get out of it!
{64285}{64351}l've got a recipe for snake. Delicious.
{64374}{64419}Fricassee of reptile.
{64441}{64492}Better than your dog food!
{64518}{64549}Pure protein...
{64555}{64643}...minerals, vitamins.|A man's gotta look after himself.
{64677}{64735}Healthy mind, healthy body, dog.
{64753}{64810}You are what you eat, l reckon.
{64818}{64845}Get away!
{64854}{64925}You two ought to take a look|in the mirror some time.
{64927}{64970}No style, no taste.
{65026}{65055}Empty!
{65074}{65111}All this time!
{65218}{65266}That's dishonest...low!
{65371}{65434}Let's have a look at this machine of yours.
{65450}{65506}How do l know that one's not a dud?
{65528}{65560}Find out.
{65627}{65714}You've got to understand the basics|of aerodynamics in a thing like this.
{65716}{65757}Shut up, shut up!
{66831}{66907}What about me?|You're not gonna leave me here, are you?
{66993}{67034}Do what you want.
{67083}{67121}We're partners!
{67327}{67379}You and me, we're partners!
{67428}{67460}Partners!
{69104}{69135}Go! Go!
{74169}{74218}My dogs, run! The gate!
{74320}{74383}The gate! The gate!
{76366}{76410}You! You can run...
{76418}{76464}...but you can't hide!
{77083}{77127}You did a great job.
{77236}{77284}Don't go overboard now.
{77307}{77386}Don't touch, please.|lt's a precision instrument.
{77675}{77710}Don't touch!
{77959}{78027}Tell me, son...this machine of yours...
{78052}{78104}...it can take two, can it?
{78152}{78184}Possibly.
{78320}{78404}l'm okay. Just get them organized.|We're moving out tonight.
{78500}{78578}Okay, listen, everyone.|We're going out tonight.
{78588}{78647}You all know what to do,|just get on with it.
{78649}{78715}Timbo, Derek...Pappagallo's been hurt.
{78748}{78785}How's the rig?
{78806}{78851}The rig. How is she?
{78860}{78939}Cracked timing case cover. lt's broken|a couple of teeth off the timing gears.
{78941}{79015}Got a cracked timing case cover.|lt's broken...
{79017}{79078}...a couple of teeth off the timing gear.
{79086}{79139}The radiator's damaged at the core.
{79161}{79209}lt's got a cracked water pump.
{79229}{79285}lt's got a fractured injector line.
{79289}{79322}Well, what does all that mean?
{79324}{79378}Yeah, okay, but what does that mean?
{79392}{79452}-What does that mean?|-Twenty-four hours!
{79499}{79534}They got twelve!
{79557}{79592}You've got twelve!
{79821}{79879}Listen, l was wrong about you...
{79893}{79934}...and l'm sorry.
{80342}{80412}lt's a long time since|l've seen driving like that, man.
{80414}{80462}You're okay by me, son.
{80466}{80552}With you driving that rig, we got it licked!|Nice to have you aboard.
{80554}{80622}l've been saving these.|l want you to have them.
{80714}{80762}Thank you, and welcome.
{80838}{80922}lt's been a pleasure doing business|with you, but l'm leaving.
{81501}{81566}You have defied me! You will know...
{81608}{81674}...the vengeance of The Lord Humungus!
{81701}{81741}I promise you...
{81767}{81811}...nobody, nobody...
{81849}{81900}...gets out of here alive!
{83130}{83208}Who's supposed to be helping out|with the drums?
{83226}{83257}Come on!
{83449}{83507}Come on with the drums, come on!
{84480}{84528}What's wrong? Come on.
{84560}{84632}lt just seems wrong|sneaking away like this.
{84736}{84808}But you said you wanted to come,|sweetheart.
{84832}{84868}l know l did.
{84899}{84982}Look, you're scared now.|Come on, it'll be much safer up there.
{84984}{85038}What are we waiting for, eh?
{85084}{85126}This is my family.
{85160}{85223}l'm not going to leave these people.
{85255}{85290}l'm staying.
{85333}{85366}l'm sorry.
{86024}{86072}Come on, l'll show you!
{86099}{86150}l told you. He's leaving.
{86243}{86343}Look, l don't have time for long speeches,|l want you to drive the tanker.
{86390}{86419}Sorry.
{86450}{86529}We had a contract.|l kept my part of the bargain.
{86546}{86594}We'll make a new contract.
{86690}{86740}l've got all l need here.
{86749}{86846}You don't have a future.|l could offer you that. Rebuild our lives.
{86880}{86930}Buy a ticket for 2,000 miles.
{86938}{87034}You have to come, sonny.|This is where we're going. Paradise!
{87064}{87110}2,000 miles from here.
{87118}{87179}Fresh water, plenty of sunshine....
{87187}{87236}Nothing to do but breed.
{87274}{87306}No thanks.
{87327}{87399}What is it with you?|What are you looking for?
{87415}{87483}Come on, Max,|everyone's looking for something.
{87495}{87550}You happy out there, are you?
{87555}{87633}Eh? Wandering...|one day blurring into another?
{87643}{87705}You're a scavenger, Max. You're a maggot.
{87727}{87823}Do you know that? You're living|off the corpse of the old world.
{87845}{87925}Tell me your story, Max.|What burned you out, huh?
{87941}{88032}Kill one man too many? See too many|people die? Lose some family?
{88035}{88144}Oh, so that's it. You lost some family.|That make you something special, does it?
{88149}{88185}Listen to me.
{88720}{88789}Do you think you're the only one|that's suffered?
{88796}{88888}We've all been through it in here,|but we haven't given up.
{88919}{88985}We're still human beings with dignity.
{88996}{89068}But you, you're out there with the garbage.
{89096}{89134}You're nothing!
{90133}{90169}Get out, kid!
{90242}{90290}Go on, get out of here.
{90804}{90862}Go on, get out. Scat! Get out!
{91623}{91669}You're letting him go?
{91715}{91781}Well, let's keep his vehicle at least.
{91787}{91866}He fulfilled his contract.|He's an honorable man.
{91911}{91977}Okay, so who's gonna drive the tanker?
{92007}{92035}l am.
{92682}{92743}They've got you wrong,|you're not a coward.
{92745}{92803}Stupid, maybe, but not a coward.
{92830}{92891}You're making a serious mistake...
{92908}{92959}...splitting a great team.
{92989}{93055}You and me together,|think of the possibilities.
{93057}{93128}See you around, maybe.|Good-bye, good luck.
{93794}{93818}We go!
{94072}{94124}You disobey me! You puppy!
{95650}{95702}Toadie, the gas! Hurry up!
{95805}{95866}Don't waste him! lf he's alive...
{95893}{95930}...l want him!
{96667}{96751}The tanks are full, O mighty Wez,|and it's all yours.
{98051}{98101}lt's all over. Let's go!
{98436}{98477}Look! Out there.
{98696}{98728}Oh, hell!
{98787}{98833}You blew it, you fool!
{100685}{100723}Relax, partner!
{103057}{103107}l'll be driving the tanker.
{103127}{103193}We're going to crash or crash through.
{103242}{103326}Now, at this point, that's all they want:|the tanker.
{103335}{103387}So they'll come straight after us.
{103391}{103460}So we'll use that to punch our way out...
{103466}{103544}...which will give all of you a very,|very good chance.
{103548}{103586}Now, don't hesitate!
{103590}{103686}Once you're outside there,|split up and go as hard as you can.
{103715}{103771}Now, 200 miles to the north...
{103780}{103864}...there's a place with a bridge|called Powder River.
{103894}{103940}That's our rendezvous.
{103976}{104020}Give us till sunset.
{104042}{104114}lf we haven't made it by then...keep going.
{104147}{104198}Good enough for me to build,|but not to ride.
{104200}{104238}You're not coming on this tanker!
{104240}{104296}l sweated blood on this.|No bastard's gonna to tell me...
{104298}{104380}-...to ride in no lousy school bus!|-Okay, settle down!
{104382}{104431}lf it's all the same to you...
{104478}{104521}...l'll drive that tanker.
{104559}{104626}The offer is closed. Too late for deals.
{104663}{104728}No deals. l want to drive the truck.
{104745}{104806}Why? Why the big change of heart?
{104815}{104861}Believe me, l haven't got a choice.
{104863}{104919}And how do you think you'll do it?
{104923}{105014}l mean, look at you.|You couldn't even drive a wheelchair!
{105043}{105115}You should look at yourself, Max.|You're a mess.
{105145}{105191}Come on, cut the crap!
{105238}{105295}l'm the best chance you've got.
{105490}{105539}Right, let's get moving!
{107256}{107313}Move that kid! Get rid of him!
{109147}{109175}Shit!
{113858}{113889}Go! Go!
{115649}{115697}l'm all right! l'm all right!
{116652}{116695}Come on! Come on!
{119520}{119572}The tire! Shoot the tire!
{123252}{123296}Boy! Come on, jump!
{123427}{123460}We've won!
{123467}{123505}lt's over, boy.
{126168}{126220}Get the bullet!
{126328}{126365}Get the shell.
{131593}{131668}And so began the journey north...|to safety...
{131687}{131731}...to our place in the sun.
{131735}{131834}Among us we found a new leader:|The man who came from the sky...
{131839}{131883}...the Gyro Captain.
{131893}{131951}Andjust as Pappagallo had planned...
{131955}{132042}...we traveled far beyond the reach|of men on machines.
{132055}{132146}Thejuice, the preciousjuice,|was hidden in the vehicles.
{132187}{132244}As for me, I grew to manhood...
{132259}{132335}...and in the fullness of time,|I became the leader...
{132339}{132403}...the Chief of the Great Northern Tribe.
{132441}{132486}And the Road Warrior?
{132506}{132571}That was the last we ever saw of him.
{132602}{132640}He lives now...
{132672}{132720}...only in my memories.
