---
title: "European Vacation"

original_title: "National Lampoon's European Vacation"

alternative_titles:
- "Hilfe, die Amis kommen"
- "Европейские каникулы"
- "Férias Frustradas II"

imdb_id: "tt0089670"
tmdb_id: "11418"
year: "1985"
