---
title: Apocalypse Now

filename: Apocalypse-Now.srt
language: en
imdb_id: tt0078788
tmdb_id: 28
year: 1979
format: srt

matches:
- filename: Apocalypse-Now.mp4
  hash: 7b5003bd07108907
  filesize: 1048237419
