---
title: "American Psycho II: All American Girl"

alternative_titles:
- "Американский психопат 2: Стопроцентная американка"
- "American Psycho II: Der Horror geht weiter"

imdb_id: "tt0283877"
tmdb_id: "10726"
year: "2002"
