---
title: "Veer & Zaara"

original_title: "Veer-Zaara"

alternative_titles:
- "Veer und Zaara - Die Legende einer Liebe"
- "Bир и Зара: История любви"

imdb_id: "tt0420332"
tmdb_id: "4251"
year: "2004"
