---
title: Lethal Weapon 3

filename: Lethal Weapon 3 - Director's Cut (1992).srt
language: en
imdb_id: tt0104714
tmdb_id: 943
year: 1992
format: srt

matches:
- filename: Lethal Weapon 3 - Director's Cut (1992).avi
  hash: fe342051818e2ea3
  filesize: 734994432
