---
title: Wild Strawberries

original_title: Smultronstället

alternative_titles:
- Wilde Erdbeeren
- Земляничная поляна
- Morangos Silvestres

filename: Wild Strawberries [Smultronstallet]_VLiS.srt
language: en
imdb_id: tt0050986
tmdb_id: 614
year: 1957
format: srt

matches:
- filename: Wild Strawberries [Smultronstallet]_VLiS.avi
  hash: 2d8a38526616c0be
  filesize: 1291067392
