---
title: "Wild Strawberries"

original_title: "Smultronstället"

alternative_titles:
- "Wilde Erdbeeren"
- "Земляничная поляна"
- "Morangos Silvestres"

imdb_id: "tt0050986"
tmdb_id: "614"
year: "1957"
