---
title: The Parallax View

alternative_titles:
- Zeuge einer Verschwörung
- À cause d'un assassinat
- Винтовка с оптическим прицелом

filename: The Parallax View.srt
language: en
imdb_id: tt0071970
tmdb_id: 17365
year: 1974
format: srt

matches:
- filename: The Parallax View.avi
  hash: e53c94d36c8fcd83
  filesize: 679514112
