---
title: Double Team

alternative_titles:
- Колония
- The Colony
- Dream Team
- La Colonia

filename: double.team.1997.internal.dvdrip.xvid-aqua.srt
language: en
imdb_id: tt0119013
tmdb_id: 9405
year: 1997
format: srt

matches:
- filename: double.team.1997.internal.dvdrip.xvid-aqua.avi
  hash: 74e909f10d48f396
  filesize: 734099456
