---
title: "Wicked City"

original_title: "Yôjû toshi"

alternative_titles:
- "Poderes Eróticos"
- "La cité interdite"
- "La città delle bestie incantatrici"

imdb_id: "tt0098692"
tmdb_id: "21453"
year: "1987"
