---
title: "The Pink Panther Strikes Again"

alternative_titles:
- "Inspector Clouseau - Der beste Mann bei Interpol"
- "Розовая пантера наносит ответный удар"
- "La pantera rosa sfida l'ispettore Clouseau"

imdb_id: "tt0075066"
tmdb_id: "12268"
year: "1976"
