---
title: "A.I. Artificial Intelligence"

original_title: "Artificial Intelligence: AI"

alternative_titles:
- "A.I.: Künstliche Intelligenz"
- "A.I. intelligence artificielle"
- "Искусственный разум"

imdb_id: "tt0212720"
tmdb_id: "644"
year: "2001"
