---
title: "Fight Back to School III"

original_title: "To hok wai lung 3: Lung gwoh gai nin"

alternative_titles:
- "Fight Back to School 3"
- "Tao xue wei long 3: Long guo ji nian"
- "Сопротивление в школе 3"

imdb_id: "tt0108293"
tmdb_id: "66657"
year: "1993"
