---
title: "Bad Lieutenant: Port of Call New Orleans"

original_title: "The Bad Lieutenant: Port of Call - New Orleans"

alternative_titles:
- "Bad Lieutenant - Cop ohne Gewissen"
- "Плохой лейтенант"
- "Il cattivo tenente - Ultima chiamata New Orleans"

imdb_id: "tt1095217"
tmdb_id: "11699"
year: "2009"
