---
title: "New Dragon Gate Inn"

original_title: "Sun lung moon hak chan"

alternative_titles:
- "Xin long men ke zhan"
- "Таверна Дракона"
- "L'auberge du dragon"

filename: "The_New_Dragon_Gate_Inn.srt"
language: "en"
imdb_id: "tt0105859"
tmdb_id: "40213"
year: "1992"
format: "srt"

matches:
- filename: "The_New_Dragon_Gate_Inn.avi"
  hash: "42b8c2457d731fdd"
  filesize: "734359552"
